// slatwall-ts - the MySQL connection pool and the injectable query executor.
//
// It replaces an external datasource registry [config/configApplication.cfm:L1-L2] rather than
// application code, which is why it holds process-lifetime state at all.
//
// JUDGMENT CALL: the pool below is the one module-scope CONNECTION RESOURCE in the target, held
// across warm invocations because a per-invocation pool would open and abandon connections. It is not
// the only request-independent mutable binding in the subtree: the executor built over this pool, the
// composition root in `src/handlers/bootstrap.ts`, the configuration memo in `src/lib/config.ts` and
// the logger threshold in `src/lib/logger.ts` are the others, and none of them holds request data.
//
// Every other CFML component-level cache in the slice becomes request-scoped rather than
// module-scoped, and `src/repositories/mysql/mysqlSkuRepository.ts` records the one whose legacy
// invalidation could never fire.

import { createPool } from 'mysql2/promise';
import type {
  Pool,
  PoolConnection,
  PoolOptions,
  ResultSetHeader,
  RowDataPacket,
  SslOptions,
} from 'mysql2/promise';
import type { DatabaseTlsConfig } from '../../lib/config.js';
import { appConfig } from '../../lib/config.js';
import { logger } from '../../lib/logger.js';
import { assertMySqlDialect, resolveConfiguredDialect } from './dialect.js';

/**
 * One row of a result set, keyed by column name.
 *
 * JUDGMENT CALL: values are `unknown`, and this type is deliberately not generic. Both halves of
 * that are load-bearing.
 *
 * The driver's own row type, `RowDataPacket`, declares `[column: string]: any`.
 */
export type SqlRow = Readonly<Record<string, unknown>>;

/**
 * A value that may be bound to a `?` placeholder.
 *
 * The union mirrors the driver's own bindable space, minus the shapes that are always a mistake
 * here (see `isSqlParameter`).
 *
 * CFML parity [model/dao/PriceGroupDAO.cfc:L65]: a legacy `<cfqueryparam>` declared a `cfsqltype`
 * and the engine checked the value against it. Binding through this union, checked at the
 * boundary, is that guarantee carried forward.
 */
export type SqlParameter = string | number | bigint | boolean | Date | Buffer | null;

/**
 * What a data-modifying statement reports back.
 *
 * JUDGMENT CALL: `insertId` is deliberately absent. Every in-scope entity declares
 * `fieldtype="id" generator="uuid"`, so a primary key is generated by the application and written
 * as a `varchar`, never by `AUTO_INCREMENT`.
 */
export interface SqlMutationResult {
  /**
   * Rows the statement affected. This is what a delete or update reports on.
   */
  readonly affectedRows: number;
  /**
   * Server warning count for the statement. Non-zero deserves investigation.
   */
  readonly warningStatus: number;
}

/**
 * WHO is making a write, as the write boundary is permitted to know it.
 *
 * Each is guarded by
 * `!getHibachiScope().getAccount().isNew() && getHibachiScope().getAccount().getAdminAccountFlag()`
 * note that `isNew()` is the ACCOUNT's, not the entity's - and both blocks sit inside an
 * `hasApplicationValue("initialized")` gate `model/dao/PromotionDAO.cfc`,
 * `model/dao/PromotionDAO.cfc`.
 */
export interface AuditActorContext {
  /**
   * The authenticated account, as an opaque identifier.
   *
   * ABSENT MEANS no PERSISTED ACCOUNT, which is the target's representation of the legacy
   * `getAccount().isNew()` half of the gate: the CFML scope hands back a new, empty account object
   * when nobody is signed in.
   */
  readonly accountID?: string | undefined;

  /**
   * Whether that account carries the legacy admin flag.
   */
  readonly adminAccountFlag: boolean;
}

/**
 * An actor context that stamps nothing - the shape a non-admin or anonymous request has, and the
 * safe default.
 */
export const UNATTRIBUTED_AUDIT_ACTOR: AuditActorContext = Object.freeze({
  adminAccountFlag: false,
});

/**
 * The account identifier a write may stamp, or `undefined` when the legacy gate refuses.
 *
 * Evaluated here alone, so the four repositories cannot drift apart on it: an INSERT reads
 * `undefined` as "stamp no actor", and an UPDATE renders it through
 * {@link sqlUpdateAssignment} so a stored actor is never overwritten with null.
 *
 * @param actor the request's audit actor.
 * @returns the account identifier to stamp, or `undefined` when the gate refuses.
 */
export function resolveAuditActorAccountID(actor: AuditActorContext): string | undefined {
  if (!actor.adminAccountFlag) {
    return undefined;
  }

  const accountID = actor.accountID;
  if (accountID === undefined || accountID.length === 0) {
    return undefined;
  }

  return accountID;
}

/**
 * The columns whose UPDATE assignment must never overwrite a stored value with null.
 *
 * Exported so a test can name them without restating the literals, and so the helpers below cannot
 * disagree about which columns are special.
 */
export const AUDIT_ACTOR_COLUMNS: readonly string[] = Object.freeze([
  'createdByAccountID',
  'modifiedByAccountID',
]);

/**
 * Render one `SET` assignment for an UPDATE statement.
 *
 * Every column renders as `name = ?` - EXCEPT the two audit account columns, which render as
 * `name = COALESCE(?, name)`.
 *
 * THE SECOND PARAMETER GENERALISES THE SAME MECHANISM TO A CALLER-NAMED COLUMN, AND IT EXISTS
 * BECAUSE A WHOLE-ROW UPDATE CAN ERASE A KEY IT WAS NEVER TOLD ABOUT. Repricing through
 * `processProduct_updateSkus` wrote `SwSku.productID` as SQL NULL at HTTP 200, orphaning every SKU
 * the request touched. The cause is
 * structurally identical to the audit-actor case this helper already existed for: the
 * statement bound a column the ENTITY COULD NOT REPORT. A SKU reached through the inverse
 * side of its own association - `Product.skus` - carries no back-reference to its owner, so
 * `sku.getProduct()` answered nothing and the whole-row UPDATE dutifully wrote that nothing
 * over a stored foreign key.
 *
 * Hibernate never had that failure mode, and the reason is worth stating precisely: it
 * flushed the DIRTY COLUMNS of a managed entity, and an association that was never
 * initialised is not dirty, so no assignment for it was emitted at all. A hand-built
 * whole-row UPDATE has no dirty-column knowledge to draw on. `COALESCE(?, column)` is the
 * SQL expression of the same rule: bind the value when the entity can report one, and leave
 * the stored value standing when it cannot.
 *
 * ⚠ WHAT THE CALLER IS ASSERTING BY NAMING A COLUMN HERE, stated plainly so the affordance is
 * not used casually. A column rendered this way CANNOT BE SET TO NULL BY THAT STATEMENT.
 * Naming one is therefore a claim that "no bound value" means "no change" for it and never
 * "clear it" - which is true of a many-to-one foreign key whose association may legitimately
 * be unmaterialised, and false of an ordinary nullable attribute a caller is entitled to
 * blank. Every use of the parameter must record, at its own site, which behaviour it makes
 * unreachable and why nothing in scope needs it.
 *
 * THE DEFAULT IS EMPTY, SO EVERY EXISTING CALL IS UNCHANGED. The two audit-actor columns
 * remain preserved unconditionally, for every repository, whether or not a second argument is
 * supplied; the parameter only ever ADDS to that floor.
 *
 * @param columnName the column being assigned.
 * @param additionalPreservedColumns further columns this statement must resolve against the
 *   stored value rather than binding a bare placeholder. Supplied by the one adapter whose
 *   entity can legitimately fail to report a column's value; empty for every other caller.
 * @returns the assignment fragment, with its single placeholder.
 */
export function sqlUpdateAssignment(
  columnName: string,
  additionalPreservedColumns: readonly string[] = [],
): string {
  if (AUDIT_ACTOR_COLUMNS.includes(columnName) || additionalPreservedColumns.includes(columnName)) {
    return sqlPreservingUpdateAssignment(columnName);
  }

  return `${columnName} = ?`;
}

/**
 * Render one `SET` assignment that resolves a bound null against the value the row already holds.
 *
 * The same `COALESCE(?, name)` fragment {@link sqlUpdateAssignment} emits for the two audit account
 * columns, published on its own so a repository can apply it to a column of ITS choosing without
 * either restating the literal or widening the shared helper's rule for every table at once.
 *
 * WHY A SECOND ENTRY POINT RATHER THAN A SECOND COLUMN IN {@link AUDIT_ACTOR_COLUMNS}. That list
 * is consulted by NAME for every UPDATE statement in the subtree, so adding a column to it changes
 * every table that happens to carry a column of that name. The audit columns can be treated that way
 * because their rule is genuinely universal - `preUpdate` behaves identically wherever they appear. A
 * MANDATORY FOREIGN KEY is not universal: it is one statement's own invariant, and the statement that
 * owns it is the only place that may declare it.
 *
 * THE ONE CONSUMER, AND THE DEFECT THAT ADDED IT. `MysqlSkuRepository`'s update renders
 * `SwSku.productID` through this helper. A CRITICAL runtime finding had `processProduct_updateSkus`
 * bind that column from a product association its fetch shape never materializes, so an update meant
 * to change two price columns ERASED the parent key of every row it touched - four of five SKUs on the
 * measured product - leaving them unreachable by identity and dropping them out of the product feed.
 * The caller that caused it now names the parent explicitly, and this fragment is the floor beneath
 * that fix: a bound null can no longer erase a stored parent key, whatever a future caller omits.
 *
 * MySQL evaluates the self-reference against the value the row held before the statement, exactly as
 * it does for the audit columns, so no extra round trip and no read-modify-write race is introduced.
 *
 * @param columnName the column being assigned.
 * @returns the assignment fragment, with its single placeholder.
 */
export function sqlPreservingUpdateAssignment(columnName: string): string {
  return `${columnName} = COALESCE(?, ${columnName})`;
}

/**
 * The value an updated row will hold for `modifiedByAccountID` once the statement above has run -
 * the TypeScript mirror of its `COALESCE`.
 *
 * Repositories hand back a fresh entity describing the row they just wrote, and that description
 * has to agree with the row.
 *
 * @param actor the request's audit actor.
 * @param previouslyStored the value the row held before this update.
 * @returns the value the row now holds.
 */
export function resolveStampedModifiedByAccountID(
  actor: AuditActorContext,
  previouslyStored: string | undefined,
): string | undefined {
  return resolveAuditActorAccountID(actor) ?? previouslyStored;
}

/**
 * The narrow execution surface every repository receives.
 *
 * JUDGMENT CALL: constructor injection exists for two reasons that both matter. First, it makes
 * the emitted SQL text and the bound parameter array assertable without A LIVE SERVER.
 *
 * JUDGMENT CALL: there is no `query` method, and there is no way to reach one through this
 * interface.
 */
export interface PreparedStatementExecutor {
  /**
   * Runs a result-set statement and returns its rows.
   *
   * @param sql The statement, owned by the calling repository or by a module under
   * `src/repositories/mysql/sql/`.
   * @param params Values for the positional `?` placeholders, in order.
   * @returns The rows, each keyed by column name with `unknown` values.
   * @throws An error named `SqlParameterError` when any element of `params` is not bindable,
   * raised before the statement is sent.
   */
  execute(sql: string, params?: readonly unknown[]): Promise<readonly SqlRow[]>;

  /**
   * Runs a data-modifying statement and returns what it affected.
   *
   * @param sql An `INSERT`, `UPDATE` or `DELETE` statement.
   * @param params Values for the positional `?` placeholders, in order.
   * @returns The affected-row count and the server warning count.
   * @throws An error named `SqlParameterError` when any element of `params` is not bindable,
   * raised before the statement is sent.
   */
  executeMutation(sql: string, params?: readonly unknown[]): Promise<SqlMutationResult>;

  /**
   * Runs `work` as one all-or-nothing unit against a single connection.
   *
   * This is the replacement for the ambient `cftransaction` the ORM opened around the legacy save
   * and delete cascades.
   *
   * @param work The unit of work.
   * @returns Whatever `work` resolves to, after the commit has succeeded.
   * @throws Whatever `work` throws, after the transaction has been rolled back and the connection
   * released; or whatever the driver raises acquiring the connection.
   */
  transaction<T>(work: (tx: PreparedStatementExecutor) => Promise<T>): Promise<T>;
}

// Two distinct faults, two distinct types, following the pattern already established by
// `src/repositories/mysql/dialect.ts`: the class is local, it sets an explicit `name`.

/**
 * The largest `IN`-list placeholder count this port will render.
 *
 * Not an invented limit - it is the MySQL client/server protocol's own ceiling.
 */
export const MAX_PLACEHOLDER_COUNT = 65535;

/**
 * Whether a statement carrying `count` placeholders could be prepared at all.
 *
 * @param count how many placeholders the statement would carry, including any that are not part of
 * the caller's list.
 * @returns `true` when a statement of that width is preparable.
 */
export function isPreparablePlaceholderCount(count: number): boolean {
  return Number.isSafeInteger(count) && count >= 0 && count <= MAX_PLACEHOLDER_COUNT;
}

/**
 * A caller asked for a placeholder list that cannot be rendered.
 */
class SqlPlaceholderCountError extends Error {
  /**
   * The rejected count, kept for programmatic inspection.
   */
  readonly count: number;

  constructor(count: number) {
    super(
      [
        `An IN-list placeholder count must be a safe integer from 1 to ${String(MAX_PLACEHOLDER_COUNT)};`,
        `received ${String(count)}.`,
        'MySQL cannot parse IN (), so a zero-length list must be short-circuited by the caller',
        'rather than rendered: an empty list means the predicate contributes nothing. The legacy',
        'code branches the same way at model/dao/PromotionDAO.cfc:L121, :L125 and',
        'model/dao/ProductDAO.cfc:L65.',
        'The upper bound is the two-byte placeholder count of COM_STMT_PREPARE_OK, so a larger',
        'statement could not be prepared by the server in any case.',
      ].join(' '),
    );
    this.name = 'SqlPlaceholderCountError';
    this.count = count;
  }
}

/**
 * A caller passed something that cannot be bound to a `?` placeholder.
 */
class SqlParameterError extends Error {
  /**
   * Zero-based position of the offending parameter within the array.
   */
  readonly parameterIndex: number;

  /**
   * The offending value's JavaScript type or constructor name. Never its value.
   */
  readonly receivedType: string;

  constructor(parameterIndex: number, receivedType: string) {
    super(
      [
        `Parameter at index ${String(parameterIndex)} is not bindable: received ${receivedType}.`,
        'Bind a string, number, bigint, boolean, Date, Buffer or null.',
        'Use null for SQL NULL - undefined is not bindable, and the driver excludes it from the',
        'value type of a prepared statement deliberately.',
        'Convert a Money or Decimal to a decimal STRING first, so currency never round-trips',
        'through a floating-point number.',
        'Do not pass an array: a prepared statement does not expand IN (?), so build the',
        'placeholders with sqlPlaceholderList and bind one parameter per element.',
      ].join(' '),
    );
    this.name = 'SqlParameterError';
    this.parameterIndex = parameterIndex;
    this.receivedType = receivedType;
  }
}

// Placeholder binds one scalar, always, and the consequence is worse than losing the extra values:
// `WHERE x IN (?)` bound with `'a,b,c'` becomes an equality against the whole comma-joined STRING.
//
// TODO [model/dao/ProductDAO.cfc:L64]: "Remove this conditional when railo and ACF match how they
// handle arrays for '`IN`' clause". Carried over verbatim as a flagged TODO, not silently
// completed.
// !! THE `IN (?)` CONTRACT - READ THIS BEFORE WRITING ANY REPOSITORY QUERY

/**
 * @param count How many values will be bound, which must equal the length of the array passed to
 * `execute`.
 * @returns The comma-separated placeholder body, WITHOUT the surrounding parentheses, so the
 * caller keeps the parentheses visible in its own SQL.
 * @throws An error named `SqlPlaceholderCountError` when `count` is not a safe integer in range -
 * including zero, which would render the unparseable `IN ()` and must instead be short-circuited
 * by the caller.
 */
export function sqlPlaceholderList(count: number): string {
  // The range check precedes the allocation deliberately: rejecting after `new Array(count)` would
  // already have committed the memory this guard exists to refuse.
  if (!Number.isSafeInteger(count) || count < 1 || count > MAX_PLACEHOLDER_COUNT) {
    throw new SqlPlaceholderCountError(count);
  }

  return new Array<string>(count).fill('?').join(', ');
}

/**
 * The widest tuple this builder will render.
 *
 * Both current callers write two columns, and the widest link table in the whole in-scope schema
 * is a two-column join row - the tables carry no surrogate key.
 */
export const MAX_TUPLE_ROW_WIDTH = 64;

/**
 * The application batch ceiling: how many tuples one statement may carry.
 */
export const SQL_TUPLE_ROW_LIMIT = 1000;

// `MAX_TUPLE_ROW_WIDTH * SQL_TUPLE_ROW_LIMIT` is 64,000, which is below the 65,535 placeholder
// ceiling of `COM_STMT_PREPARE_OK`, so no admissible width/count pair can exceed what the server
// could prepare.
if (MAX_TUPLE_ROW_WIDTH * SQL_TUPLE_ROW_LIMIT > MAX_PLACEHOLDER_COUNT) {
  throw new Error(
    `The tuple builder's own limits are inconsistent with the protocol ceiling: ` +
      `${String(MAX_TUPLE_ROW_WIDTH)} x ${String(SQL_TUPLE_ROW_LIMIT)} exceeds ` +
      `${String(MAX_PLACEHOLDER_COUNT)} bindable placeholders. Lower one of the two limits.`,
  );
}

/**
 * Raised when a tuple body is asked for in a shape this builder refuses.
 */
class SqlTupleShapeError extends Error {
  /**
   * Which dimension was rejected, for programmatic inspection.
   */
  readonly dimension: 'rowWidth' | 'rowCount';

  /**
   * The rejected value.
   */
  readonly value: number;

  constructor(dimension: 'rowWidth' | 'rowCount', value: number, limit: number) {
    super(
      [
        `A multi-row VALUES body needs a ${dimension === 'rowWidth' ? 'row width' : 'row count'}`,
        `that is a safe integer from 1 to ${String(limit)}; received ${String(value)}.`,
        'Zero is refused rather than rendered because `VALUES` with no rows is a parse error, not',
        'an empty write - the caller must skip the collection instead.',
        dimension === 'rowCount'
          ? 'A collection larger than the batch ceiling must be chunked with `chunkTupleRows` and ' +
            'written as successive statements inside one transaction.'
          : 'No in-scope link table is this wide, so a width beyond the ceiling indicates a caller defect.',
      ].join(' '),
    );
    this.name = 'SqlTupleShapeError';
    this.dimension = dimension;
    this.value = value;
  }
}

/**
 * The `VALUES` body of a multi-row insert: `(?, ?)` for one row, `(?, ?), (?, ?)` for two.
 *
 * @param rowWidth Columns per tuple.
 * @param rowCount How many tuples to render.
 * @returns The comma-separated tuple bodies, parentheses included, ready to follow the `VALUES`
 * keyword.
 * @throws An error named `SqlTupleShapeError` when either dimension is out of range.
 */
export function sqlTuplePlaceholderList(rowWidth: number, rowCount: number): string {
  if (!Number.isSafeInteger(rowWidth) || rowWidth < 1 || rowWidth > MAX_TUPLE_ROW_WIDTH) {
    throw new SqlTupleShapeError('rowWidth', rowWidth, MAX_TUPLE_ROW_WIDTH);
  }

  if (!Number.isSafeInteger(rowCount) || rowCount < 1 || rowCount > SQL_TUPLE_ROW_LIMIT) {
    throw new SqlTupleShapeError('rowCount', rowCount, SQL_TUPLE_ROW_LIMIT);
  }

  const rowBody = `(${sqlPlaceholderList(rowWidth)})`;

  return new Array<string>(rowCount).fill(rowBody).join(', ');
}

/**
 * Splits a collection into batches no larger than {@link SQL_TUPLE_ROW_LIMIT}.
 *
 * The counterpart to {@link sqlTuplePlaceholderList}: it is what lets a ceiling bound the
 * allocation without bounding what a caller may legitimately write.
 *
 * @param rows The members to write.
 * @returns One or more batches, in the input's order, each of length 1 to {@link
 * SQL_TUPLE_ROW_LIMIT}.
 * @throws An error named `SqlTupleShapeError` when `rows` is empty.
 */
export function chunkTupleRows<T>(rows: readonly T[]): readonly (readonly T[])[] {
  if (rows.length === 0) {
    throw new SqlTupleShapeError('rowCount', 0, SQL_TUPLE_ROW_LIMIT);
  }

  const batches: (readonly T[])[] = [];

  for (let offset = 0; offset < rows.length; offset += SQL_TUPLE_ROW_LIMIT) {
    batches.push(rows.slice(offset, offset + SQL_TUPLE_ROW_LIMIT));
  }

  return batches;
}

/**
 * Reused for a call that binds nothing, so no array is allocated per call.
 */
const NO_PARAMETERS: readonly unknown[] = Object.freeze([]);

/**
 * Names the type of a rejected parameter without revealing the value itself.
 */
function describeRejectedType(value: unknown): string {
  if (value === null) {
    return 'null';
  }

  if (Array.isArray(value)) {
    return 'an array';
  }

  const primitiveKind = typeof value;
  if (primitiveKind !== 'object') {
    return primitiveKind;
  }

  const { constructor } = value as { readonly constructor?: { readonly name?: unknown } };
  const constructorName = constructor?.name;

  if (typeof constructorName !== 'string' || constructorName.length === 0) {
    // A null-prototype object, or one whose constructor has been stripped.
    return 'an object';
  }

  // A plain object literal reports its constructor as `Object`, and saying "an instance of Object"
  // would be needlessly obscure about the commonest case.
  return constructorName === 'Object' ? 'an object' : `an instance of ${constructorName}`;
}

/**
 * Whether a value may be bound to a `?` placeholder.
 *
 * CFML parity [model/dao/PriceGroupDAO.cfc:L65]: `<cfqueryparam cfsqltype="cf_sql_timestamp">`
 * declared the type it expected and the engine checked the value against it.
 */
function isSqlParameter(value: unknown): value is SqlParameter {
  if (value === null) {
    return true;
  }

  switch (typeof value) {
    case 'string':
    case 'bigint':
    case 'boolean':
      return true;
    case 'number':
      return Number.isFinite(value);
    default:
      break;
  }

  if (value instanceof Date) {
    return Number.isFinite(value.getTime());
  }

  return Buffer.isBuffer(value);
}

/**
 * Checks every parameter and returns them in the array shape the driver takes.
 *
 * The check runs before the statement is sent, so an unbindable value never reaches the server and
 * never occupies a pooled connection.
 */
function toBoundParameters(params: readonly unknown[]): SqlParameter[] {
  const bound: SqlParameter[] = [];

  for (const [index, value] of params.entries()) {
    if (!isSqlParameter(value)) {
      throw new SqlParameterError(index, describeRejectedType(value));
    }

    bound.push(value);
  }

  return bound;
}

/**
 * The site name reported if the configured dialect is not MySQL.
 *
 * Follows the constant-per-site convention of `src/repositories/mysql/dialect.ts`, so the citation
 * and the failure message cannot drift apart.
 */
const POOL_CREATION_SITE =
  'config/configApplication.cfm:L2 (the configured datasource, opened here as a mysql2 pool)';

/**
 * The connection time zone, fixed at UTC.
 *
 * The legacy behaviour it replaces was equally implicit but differently so: CFML `now()` returns
 * SERVER-LOCAL time, and the in-scope DAOs call it six times - [model/dao/PromotionDAO.cfc:L117]
 * and [model/dao/PromotionDAO.cfc:L306], plus [model/dao/PriceGroupDAO.cfc:L65],
 * [model/dao/PriceGroupDAO.cfc:L70].
 */
const POOL_TIMEZONE = 'Z';

/**
 * Turns the resolved transport posture into the driver's `ssl` options, or `undefined` when
 * transport is deliberately off.
 *
 * JUDGMENT CALL: `rejectUnauthorized` is a literal `true` in both arms and is never read from
 * configuration.
 *
 * @param tls The resolved posture from `src/lib/config.ts`, already validated, and already refused
 * if it named `disabled` in production or for a non-loopback host.
 * @returns The driver's `ssl` options, or `undefined` for `disabled`.
 */
function buildTlsOptions(tls: DatabaseTlsConfig): SslOptions | undefined {
  if (tls.mode === 'disabled') {
    return undefined;
  }

  const verification: SslOptions = {
    rejectUnauthorized: true,
    verifyIdentity: tls.mode === 'verify-identity',
    minVersion: tls.minimumVersion,
  };

  return tls.certificateAuthority === undefined
    ? verification
    : { ...verification, ca: tls.certificateAuthority };
}

/**
 * Builds the driver options from validated configuration.
 *
 * Every value comes from `src/lib/config.ts`, the owner of the database and runtime keys and the
 * only module this file consults for them - see the ownership split in the module header.
 *
 * Credential on `DatabaseConnectionConfig` is a prototype getter over a private field, so it is
 * not an own enumerable property.
 */
function buildPoolOptions(): PoolOptions {
  const { database, pool, tls } = appConfig.load();
  const ssl = buildTlsOptions(tls);

  const options: PoolOptions = {
    host: database.host,
    port: database.port,
    database: database.database,
    user: database.user,
    password: database.password,
    connectionLimit: pool.connectionLimit,
    connectTimeout: pool.connectTimeout,
    maxIdle: pool.maxIdle,
    idleTimeout: pool.idleTimeout,
    timezone: POOL_TIMEZONE,
  };

  // The key is ADDED only when transport is on, rather than being present with an `undefined`
  // value.
  return ssl === undefined ? options : { ...options, ssl };
}

/**
 * The container's pool, once something has asked for it.
 *
 * This is the sanctioned module-scope state described in the file header, and it is the only
 * mutable module-level binding in this file that holds a resource.
 */
let memoizedPool: Pool | undefined;

/**
 * The executor wrapping `memoizedPool`, so repeated wiring returns one object.
 */
let memoizedExecutor: PreparedStatementExecutor | undefined;

/**
 * The container's MySQL pool, created on first use and reused thereafter.
 *
 * CFML parity [config/configORM.cfm:L4-L7]: the legacy host treated an unreachable datasource as
 * fatal, not as a degraded mode.
 *
 * Note that constructing a pool does not open a connection.
 *
 * @returns The one pool for this container.
 * @throws An error named `ConfigurationError`, raised by `src/lib/config.ts`, when the environment
 * contract is unsatisfied.
 */
export function getConnectionPool(): Pool {
  if (memoizedPool !== undefined) {
    return memoizedPool;
  }

  // JUDGMENT CALL: the dialect is refused here, at the one place a pool is built, rather than
  // assumed. `src/repositories/mysql/dialect.ts` owns the value - it is imported, never re-derived
  // and its own documentation invites callers to assert early.
  const dialect = resolveConfiguredDialect();
  assertMySqlDialect(dialect, POOL_CREATION_SITE);

  memoizedPool = createPool(buildPoolOptions());

  // What remains is the only fact this line was ever needed for: a pool was constructed in this
  // container, exactly once.
  logger.info('MySQL connection pool created');

  return memoizedPool;
}

/**
 * Adapts a pool to the narrow executor contract.
 *
 * Kept separate from `getConnectionPool` so that the adaptation - parameter admission, the driver
 * call, and the re-typing of rows.
 *
 * A test does not need this function: `PreparedStatementExecutor` is three methods wide and a
 * suite implements it directly rather than imitating a pool - including `transaction`.
 *
 * @param pool The pool every statement will be sent through.
 * @returns A frozen executor.
 */
export function createPoolExecutor(pool: Pool): PreparedStatementExecutor {
  return Object.freeze({
    async execute(
      sql: string,
      params: readonly unknown[] = NO_PARAMETERS,
    ): Promise<readonly SqlRow[]> {
      // The driver's row type is named here and nowhere else in the port.
      const [rows] = await pool.execute<RowDataPacket[]>(sql, toBoundParameters(params));

      return rows;
    },

    async executeMutation(
      sql: string,
      params: readonly unknown[] = NO_PARAMETERS,
    ): Promise<SqlMutationResult> {
      const [header] = await pool.execute<ResultSetHeader>(sql, toBoundParameters(params));

      return Object.freeze({
        affectedRows: header.affectedRows,
        warningStatus: header.warningStatus,
      });
    },

    async transaction<T>(work: (tx: PreparedStatementExecutor) => Promise<T>): Promise<T> {
      // One connection for the whole unit - a pooled connection, not the pool.
      const connection = await pool.getConnection();

      try {
        await connection.beginTransaction();

        const result = await work(createConnectionExecutor(connection));

        await connection.commit();

        return result;
      } catch (error: unknown) {
        await rollBackQuietly(connection);
        throw error;
      } finally {
        // Released on every path, including the one where the rollback itself failed.
        connection.release();
      }
    },
  });
}

/**
 * Rolls back, and refuses to let a rollback failure mask the original one.
 *
 * Nothing is logged but the fact - no value, and not the driver error's own message.
 */
async function rollBackQuietly(connection: PoolConnection): Promise<void> {
  try {
    await connection.rollback();
  } catch {
    logger.error('MySQL transaction rollback failed');
  }
}

/**
 * An executor pinned to one connection, for the duration of one transaction.
 *
 * Not exported: the only way to obtain one is to be inside
 * `PreparedStatementExecutor.transaction`.
 *
 * @param connection The pooled connection carrying the open transaction.
 * @returns A frozen executor whose every statement runs on `connection`.
 */
function createConnectionExecutor(connection: PoolConnection): PreparedStatementExecutor {
  const boundExecutor: PreparedStatementExecutor = Object.freeze({
    async execute(
      sql: string,
      params: readonly unknown[] = NO_PARAMETERS,
    ): Promise<readonly SqlRow[]> {
      const [rows] = await connection.execute<RowDataPacket[]>(sql, toBoundParameters(params));

      return rows;
    },

    async executeMutation(
      sql: string,
      params: readonly unknown[] = NO_PARAMETERS,
    ): Promise<SqlMutationResult> {
      const [header] = await connection.execute<ResultSetHeader>(sql, toBoundParameters(params));

      return Object.freeze({
        affectedRows: header.affectedRows,
        warningStatus: header.warningStatus,
      });
    },

    transaction<T>(work: (tx: PreparedStatementExecutor) => Promise<T>): Promise<T> {
      return work(boundExecutor);
    },
  });

  return boundExecutor;
}

/**
 * The executor the composition root wires into every repository.
 *
 * This is the single line `src/handlers/bootstrap.ts` needs, and it is the only place production
 * code should turn a pool into an executor.
 *
 * @returns The one executor over the one pool.
 * @throws Whatever `getConnectionPool` throws on the first call.
 */
export function getPreparedStatementExecutor(): PreparedStatementExecutor {
  memoizedExecutor ??= createPoolExecutor(getConnectionPool());

  return memoizedExecutor;
}

/**
 * Closes the pool and returns this module to its pre-creation state.
 *
 * JUDGMENT CALL: teardown is explicit and caller-driven. No `process.on('SIGTERM')` handler is
 * registered, deliberately.
 *
 * The memoized bindings are cleared before the close is awaited, so the module is left in a state
 * a later call can rebuild from - which is what lets a harness close and reopen.
 *
 * @returns A promise that settles once the driver has closed the pool.
 */
export async function closeConnectionPool(): Promise<void> {
  const pool = memoizedPool;

  memoizedPool = undefined;
  memoizedExecutor = undefined;

  if (pool === undefined) {
    return;
  }

  await pool.end();

  logger.info('MySQL connection pool closed');
}
