// slatwall-ts - Promotion entity. Port of model/entity/Promotion.cfc (181 lines).
//
// The `SwPromotion` row: the hub of the promotion aggregate.
//
// THE COMPONENT DECLARATION, VERBATIM [model/entity/Promotion.cfc:L49]
//
//   component displayname="Promotion" entityname="SlatwallPromotion" table="SwPromotion"
//   persistent="true" extends="HibachiEntity" cacheuse="transactional"
//   hb_serviceName="promotionService" hb_permission="this" {
//
// Schema continuity is binding, so entity property metadata IS the contract: table `SwPromotion`,
// entity name `SlatwallPromotion`, no migration, no rename, no new table, no column change. Every
// `hb_*` attribute value is carried forward verbatim as an inert string so the legacy admin can
// still resolve it, and no i18n runtime is introduced - JavaRB is not ported. The declaration
// carries NO `accessors=`, NO `output=` and NO `hb_processContexts`.
//
// LEGACY-NOTE [model/entity/Promotion.cfc:L49]: `hb_permission="this"` is the SELF-REFERENTIAL form
// and appears on no other in-scope entity - every sibling in this aggregate uses a dotted path
// instead (`"promotion.promotionPeriods"` at [model/entity/PromotionPeriod.cfc:L49],
// `"promotion.promotionCodes"` at [model/entity/PromotionCode.cfc:L49]). Preserved verbatim;
// permission evaluation is a framework concern that is not ported.
//
// LEGACY-NOTE [model/entity/Promotion.cfc:L49]: the `extends` chain is THREE levels deep, not two.
// `extends="HibachiEntity"` is UNQUALIFIED, so it resolves to the local
// model/entity/HibachiEntity.cfc (274 lines), which itself extends
// `Slatwall.org.Hibachi.HibachiEntity`. The intermediate class reaches outward through twelve
// `getService(...)` sites and NONE is ported: an entity reaching outward through a service locator
// is exactly the pattern the ESLint `no-restricted-imports` domain boundary exists to make
// impossible.
//
// [org/Hibachi/HibachiEntity.cfc:L507-L565] is an `onMissingMethod` dispatcher matching eleven
// method-name patterns - hasUniqueOrNull*, hasUnique*, hasAny*, get*AssignedIDList, get*ID,
// get*Options, get*OptionsSmartList, get*SmartList, get*Struct, get*Count, and a
// `getAttributeValue` fallback - TERMINATING IN A THROW AT L565. Dynamic dispatch is not emulated:
// no Proxy, no index signature, no `evaluate()`, no string-keyed method lookup, no `variables.`
// scope object. Only concretely-called members are authored. NONE of the eleven patterns is a
// singular `has<Property>`, so the three containment probes below do NOT resolve through that
// dispatcher - they are generated by the CFML ORM for a collection declared with `singularname`,
// which L62, L63 and L64 each are.
//
// THE ANTI-CONTRACT IS AS BINDING AS THE CONTRACT. There is NO `promotionAccounts` collection on
// this entity and this class must never gain one: model/entity/Promotion.cfc contains zero
// occurrences of `promotionAccount`, and its fieldtype census finds exactly three collections -
// L62, L63, L64 - and no fourth. That absence is exactly WHY
// [model/entity/PromotionAccount.cfc:L90-L95] is a confirmed throwing defect: its `setPromotion`
// calls `hasPromotionAccount( this )` and `getPromotionAccounts()` on a Promotion, neither exists,
// neither is generated because no such collection is declared, and the call falls through to the
// throw at [org/Hibachi/HibachiEntity.cfc:L565]. Adding the far side here would SILENTLY REPAIR
// that defect, invent behaviour the legacy system does not have, and break schema continuity, since
// there is no `SwPromotion` -> `SwPromotionAccount` inverse mapping to honour. The same rule is
// published from promotionAccount.ts, promotionPeriod.ts and promotionCode.ts.
//
// LEGACY-NOTE [model/entity/Promotion.cfc:L62, L79, L117, L154, L159, L171, L69, L75, L93-L94,
// L179-L180, L141-L145, L48-L86]: THE COSMETIC WARTS, RECORDED COLLECTIVELY AND ONCE. None is a
// defect and none changes behaviour: trailing whitespace on L62 and L79; a stray TAB after L117's
// closing brace; TAB-plus-three-spaces indentation on L154 and L159; spaces inside the call parens
// at L171; lower-case `p` in the L69 and L75 banners; double blank lines at L93-L94 and L179-L180;
// capital-P `PromotionPeriod` argument names at L141/L144; and MIXED LINE ENDINGS - exactly 39
// lines, L48 through L86, are CRLF and every other line is LF. Nothing is reproduced from this
// list.
//
// LEGACY-NOTE [model/entity/Promotion.cfc:L176-L178]: THE ORM EVENT HOOKS BLOCK IS EMPTY, so this
// class authors no lifecycle-maintenance method of any kind - no `preInsert`, no `preUpdate`, no
// materialized-path column, no generated value to seed. Four in-scope entities DO carry hooks, each
// with its own ordering: [model/entity/Category.cfc:L126, L131] with `super` FIRST,
// [model/entity/PriceGroup.cfc:L206, L211] with path maintenance BEFORE `super`,
// [model/entity/ProductType.cfc:L305, L310], and [model/entity/PromotionCode.cfc:L179], which is
// insert-only. `Promotion` is a fifth pattern: none at all.
//
// LEGACY-NOTE [model/entity/Promotion.cfc:L83-L134]: NO CLOCK IS INJECTED INTO THIS ENTITY AND NONE
// MAY BE ADDED. The component contains ZERO `now()` calls, because every date comparison in this
// aggregate lives one level down, in `PromotionPeriod.getCurrentFlag()`
// [model/entity/PromotionPeriod.cfc:L137-L146] and `PromotionCode.getCurrentFlag()`
// [model/entity/PromotionCode.cfc:L85-L94], each of which owns its own injected clock.
// `Promotion.getCurrentFlag()` is therefore TRANSITIVELY clock-dependent, which requires nothing
// here: no clock parameter, no date parameter on any method, no date-related import.
//
// Every method keeps its exact legacy arity - the project permits exactly one entity-layer
// signature widening and it is spent on `PromotionPeriod.isCurrent(now: Date)`, so the children's
// `getCurrentFlag()` is called with NO argument. Nothing private becomes public. Defects are
// reproduced, never repaired: a method that throws at runtime today throws here too.

import { cfBoolean } from '../../lib/cfml/truthiness.js';
import type { PromotionApplied } from './promotionApplied.js';
import type { PromotionCode } from './promotionCode.js';
import type { PromotionPeriod } from './promotionPeriod.js';

/**
 * The shapes a hydrated `ormtype="boolean"` column may arrive in from the driver.
 *
 * Declared LOCALLY AND UN-EXPORTED rather than imported, and that is a considered choice with two
 * reasons behind it. First, the legal import surface of this file is exactly four statements, and
 * `@typescript-eslint/consistent-type-imports` is configured with
 *   `fixStyle: 'separate-type-imports'`,
 * so pulling `CfBooleanInput` in would necessarily add a FIFTH statement for a type alias rather
 * than for a capability. Second, TypeScript is structural: this union is member-for-member the
 * union `cfBoolean` accepts, so it is assignable without any assertion, and the single value import
 * above remains the only coupling to `src/lib/`.
 *
 * `undefined` is deliberately NOT a member. Absence is expressed by omitting the constructor key,
 * which `exactOptionalPropertyTypes` keeps distinguishable from a present `null` - and the two
 * states mean different things here, as the `activeFlag` field documents.
 */
type PersistedBooleanColumn = string | number | boolean | null;

/**
 * The ORM default declared for `activeFlag` at [model/entity/Promotion.cfc:L56], carried over as
 * the literal `"1"` rather than as `true`.
 *
 * Keeping the raw literal means the coercion that the legacy engine applied to the default is the
 * SAME coercion this port applies, performed by the same helper, instead of being short-circuited
 * by a hand-written boolean. It is a frozen string constant, so it carries no state between two
 * invocations that happen to share a warm container.
 */
const ACTIVE_FLAG_ORM_DEFAULT = '1' as const;

/**
 * The one member [model/entity/Promotion.cfc:L127] reaches on a promotion code.
 *
 * THE CROSS-FILE GAP THIS EXISTS TO SURFACE. `getPromotionCodesDeletableFlag()` calls
 * `promotionCode.isDeletable()`, and that call does NOT resolve to anything on
 * model/entity/PromotionCode.cfc - that component declares no `isDeletable()` and its Custom
 * Validation banner pair at L157/L159 is empty. It resolves because `isDeletable()` is a method on
 * the FRAMEWORK BASE at [org/Hibachi/HibachiEntity.cfc:L204-L206], which
 * [model/entity/Promotion.cfc:L170] and [model/entity/PromotionPeriod.cfc:L87] both OVERRIDE - L170
 * sitting under the `// START: Overridden Methods` banner at L168 being the proof. So the legacy
 * call RESOLVES AND DOES NOT THROW; it is not a defect. The base is deliberately not ported, which
 * turns an inherited method into a structural dependency: `promotionCode.ts` declares no
 * `isDeletable()`.
 *
 * The member is NOT invented on that file, nothing is widened to `any`, no suppression comment is
 * used, and the call is NOT silently dropped. Instead this narrow structural contract names the
 * single member the legacy body reaches, a runtime probe decides whether a given promotion code
 * carries it, and `getPromotionCodesDeletableFlag()` calls it exactly as the legacy does when it is
 * present. When it is absent the method raises, because papering over the gap with a fabricated
 * boolean is forbidden: both answers are load-bearing on a delete path, and `true` would report a
 * promotion as safely deletable while its codes are still attached to live orders.
 *
 * THE CROSS-FILE FOLLOW-UP THAT CLOSES THE CONTRACT: declare `isDeletable(): boolean` on
 * `promotionCode.ts` reproducing [org/Hibachi/HibachiEntity.cfc:L204-L206], whose body is
 * `!getService("hibachiValidationService").validate(object=this, context="delete",
 * setErrors=false).hasErrors()`. For that entity the delete context is exactly one rule -
 * model/validation/PromotionCode.json declares
 *   `"orders": [{"contexts":"delete","maxCollection":0}]`
 * over a collection already exposed there as `getOrders()`. Once that member exists the probe
 * narrows on every call and the raise becomes unreachable, with no change to this file.
 *
 * Module-local and un-exported on purpose: this entity injects no collaborator port at all -
 * model/entity/Promotion.cfc has ZERO `getService(` sites - so nothing here may become an exported
 * port contract or a constructor-injected service handle.
 */
interface FrameworkDeletableEntity {
  isDeletable(): boolean;
}

/**
 * Whether a promotion code carries the framework-inherited `isDeletable()` described above.
 *
 * The assertion is a DOWNCAST to an intersection that merely adds the member as OPTIONAL - not a
 * widening to `any`, not a bounce through `unknown`, and not a claim that the member is present. It
 * is the narrowest construct that lets a genuine runtime question be asked in a typed language, and
 * the answer is then carried in the type by the predicate so the call site needs no further
 * assertion. `@typescript-eslint/no-unnecessary-condition` is deliberately disabled for this
 * subtree, precisely so that checks the type system believes redundant - and this one is not even
 * redundant - remain expressible.
 */
function reachesFrameworkIsDeletable(
  candidate: PromotionCode,
): candidate is PromotionCode & FrameworkDeletableEntity {
  const probe = candidate as PromotionCode & Partial<FrameworkDeletableEntity>;
  return typeof probe.isDeletable === 'function';
}

/**
 * The `SwPromotion` row: the hub entity of the promotion aggregate.
 *
 * A CLASS RATHER THAN AN INTERFACE, because the legacy entities carry behaviour and not merely
 * data: four members are non-persistent property methods with real bodies
 * [model/entity/Promotion.cfc:L83-L134] and one overrides the framework's deletability rule
 * [model/entity/Promotion.cfc:L170-L172]. Method names are the legacy CFML names VERBATIM in
 * camelCase, which is why eslint.config.mjs enables no `naming-convention`, `camelcase` or
 * `id-match` rule - including the plural in `getPromotionCodesDeletableFlag`, which
 * model/validation/Promotion.json invokes by name.
 *
 * ASSOCIATIONS ARRIVE ALREADY MATERIALIZED, AND LAZINESS IS NEVER SIMULATED:
 * `src/repositories/mysql/**` owns hydration and documents the chosen fetch shape at the producing
 * method. None of the three collections carries `lazy="extra"`, so all three are materialized.
 *
 * EVERY MEMBER IS SYNCHRONOUS - a method becomes `async` only where its legacy body reached the DAO
 * or the ORM, and nothing here does - and there is no arithmetic anywhere in this component: no
 * monetary and no currency column exists on `SwPromotion`. NO COLLABORATOR PORT IS INJECTED,
 * because model/entity/Promotion.cfc has ZERO `getService(` sites.
 */
export class Promotion {
  /**
   * [model/entity/Promotion.cfc:L52] `property name="promotionID" ormtype="string" length="32"
   * fieldtype="id" generator="uuid" unsavedvalue="" default="";`
   *
   * `length="32"` is the `SwPromotion.promotionID` column width and is recorded rather than
   * enforced - length validation is a service-tier concern and belongs to the zod schema ported
   * from model/validation/Promotion.json, not to the entity. `unsavedvalue=""` together with
   * `default=""` is what makes an unsaved row's primary key the empty string, and that sentinel is
   * load-bearing for the containment probes below.
   */
  private readonly promotionID: string;

  /**
   * [model/entity/Promotion.cfc:L53] `property name="promotionName" ormtype="string";`
   *
   * NO `length`, NO `default` and - decisively - NO `notnull`, so the column is nullable. See the
   * ruling on `getPromotionName()` for why that nullability is carried into the accessor's return
   * type instead of being coalesced away.
   */
  private readonly promotionName: string | undefined;

  /** [model/entity/Promotion.cfc:L54] `ormtype="string" length="1000"`, nullable. */
  private readonly promotionSummary: string | undefined;

  /** [model/entity/Promotion.cfc:L55] `ormtype="string" length="4000"`, nullable. */
  private readonly promotionDescription: string | undefined;

  /**
   * [model/entity/Promotion.cfc:L56] `property name="activeFlag" ormtype="boolean" default="1";`
   *
   * RESOLVED ONCE, IN THE CONSTRUCTOR, AND STORED AS A `boolean`. The boolean census of this
   * component was re-verified from the verbatim read: `activeFlag` is the ONE AND ONLY persistent
   * boolean here, spelled with the lower-case `ormtype=` attribute, and there is no camelCase
   * `ormType=` variant on this component. The four `type="boolean" persistent="false"` declarations
   * at L76-L79 are NOT columns and never appear in a persisted-row shape.
   *
   * The `default="1"` is honoured rather than dropped: a promotion constructed WITHOUT the key
   * reads TRUE, exactly as a freshly-created CFML entity does. See the constructor for how that is
   * kept distinguishable from a hydrated SQL NULL, which reads FALSE.
   */
  private readonly activeFlag: boolean;

  /**
   * LEGACY-NOTE [model/entity/Promotion.cfc:L59]: `property name="defaultImage" cfc="Image"
   * fieldtype="many-to-one" fkcolumn="defaultImageID";` - `Image` is NOT one of the eighteen
   * in-scope entities, so the association is COLLAPSED TO THE INERT OPAQUE IDENTIFIER
   * `defaultImageID` and no `getDefaultImage()` accessor is authored. The FK column is preserved so
   * the `SwPromotion` schema contract is unbroken, and nothing in the slice reads any other member
   * of a promotion's default image - model/entity/Promotion.cfc never mentions `defaultImage` again
   * after L59, and no in-scope service or DAO touches it. Same treatment `category.ts` gives `site`
   * and `promotionApplied.ts` gives its three order-side FKs. The declaration carries NO
   * `fetch="join"`, and none is added: the project-wide eager-fetch census stays at exactly four
   * sites - Product.cfc L68, L69, L70 and PromotionPeriod.cfc L59.
   */
  private readonly defaultImageID: string | undefined;

  /**
   * [model/entity/Promotion.cfc:L62] `property name="promotionPeriods"
   * singularname="promotionPeriod" cfc="PromotionPeriod" fieldtype="one-to-many"
   * fkcolumn="promotionID" cascade="all-delete-orphan" inverse="true";`
   *
   * MUTABLE ARRAY, HANDED OUT LIVE. `inverse="true"` means `PromotionPeriod` owns the foreign key,
   * and model/entity/PromotionPeriod.cfc:L101 mutates THIS array in place through
   * `getPromotionPeriods()`. The FIELD is `readonly` so the binding can never be replaced while the
   * array's CONTENTS stay mutable - two different guarantees, and both are wanted.
   */
  private readonly promotionPeriods: PromotionPeriod[];

  /**
   * [model/entity/Promotion.cfc:L63] `singularname="promotionCode" cfc="PromotionCode"
   * fieldtype="one-to-many" fkcolumn="promotionID" cascade="all-delete-orphan" inverse="true"`.
   * LIVE, per model/entity/PromotionCode.cfc:L105 `arrayAppend` and L116 `arrayDeleteAt`.
   */
  private readonly promotionCodes: PromotionCode[];

  /**
   * [model/entity/Promotion.cfc:L64] `singularname="appliedPromotion" cfc="PromotionApplied"
   * fieldtype="one-to-many" fkcolumn="promotionID" cascade="all" inverse="true"`. LIVE, per
   * [model/entity/PromotionApplied.cfc:L82] `arrayAppend` and
   * [model/entity/PromotionApplied.cfc:L91] `arrayDeleteAt`. This is also the collection
   * `isDeletable()` counts.
   *
   * LEGACY-NOTE [model/entity/Promotion.cfc:L62-L64]: THE CASCADE ASYMMETRY IS REAL AND IS
   * PRESERVED RATHER THAN NORMALISED. `promotionPeriods` (L62) and `promotionCodes` (L63) are each
   * `cascade="all-delete-orphan"` while `appliedPromotions` (L64) is plain `cascade="all"`, so
   * orphan removal applies to two of the three. Honouring the cascade obligation itself belongs to
   * `src/repositories/mysql/**`.
   */
  private readonly appliedPromotions: PromotionApplied[];

  /** [model/entity/Promotion.cfc:L67] `remoteID` - the integration correlation column. */
  private readonly remoteID: string | undefined;

  /** [model/entity/Promotion.cfc:L70] `hb_populateEnabled="false" ormtype="timestamp"`. */
  private readonly createdDateTime: Date | undefined;

  /**
   * LEGACY-NOTE [model/entity/Promotion.cfc:L71]: `property name="createdByAccount"
   * hb_populateEnabled="false" cfc="Account" fieldtype="many-to-one"
   * fkcolumn="createdByAccountID";`
   *
   * `Account` is explicitly OUT OF SCOPE, so this many-to-one is collapsed to the inert opaque
   * identifier `createdByAccountID`. An audit column needs no behaviour from the far side, the FK
   * is preserved so the schema contract is unbroken, and `hb_populateEnabled="false"` is carried
   * forward verbatim in this note. Identical treatment to every other in-scope entity.
   */
  private readonly createdByAccountID: string | undefined;

  /** [model/entity/Promotion.cfc:L72] `hb_populateEnabled="false" ormtype="timestamp"`. */
  private readonly modifiedDateTime: Date | undefined;

  /**
   * [model/entity/Promotion.cfc:L73] `hb_populateEnabled="false" cfc="Account"
   * fieldtype="many-to-one" fkcolumn="modifiedByAccountID"` - collapsed exactly as
   * `createdByAccountID` above, and for the same reason.
   */
  private readonly modifiedByAccountID: string | undefined;

  /**
   * [model/entity/Promotion.cfc:L76]
   *   `property name="currentFlag" type="boolean" persistent="false";` -
   * the memo behind `getCurrentFlag()`.
   *
   * REQUEST-SCOPED, NOT MODULE-SCOPED. The legacy memo lives in the component's `variables` scope,
   * which on a warm Lambda container would persist between unrelated invocations and could leak one
   * request's answer into another's. Entity instances here are created per request by the
   * repository, so the memo is instance-scoped. There is no invalidation in the legacy and none is
   * added.
   */
  private currentFlag: boolean | undefined;

  /** [model/entity/Promotion.cfc:L77] memo behind `getCurrentPromotionPeriodFlag()`. */
  private currentPromotionPeriodFlag: boolean | undefined;

  /** [model/entity/Promotion.cfc:L78] memo behind `getCurrentPromotionCodeFlag()`. */
  private currentPromotionCodeFlag: boolean | undefined;

  // [model/entity/Promotion.cfc:L79]
  //   `property name="promotionCodesDeletableFlag" type="boolean" persistent="false";`
  // DELIBERATELY HAS NO BACKING FIELD. That is not an omission - it is the faithful reproduction of
  // the four-way key mismatch documented on `getPromotionCodesDeletableFlag()` below, whose legacy
  // memo can never take effect. A field written but never read would be dead state that
  // misrepresents the behaviour, and a field written AND read would change how many times
  // `PromotionCode.isDeletable()` is invoked, which is observable. So there is none.

  /**
   * Constructed from a repository row plus its materialized associations.
   *
   * Never constructed from a sibling entity module: row-to-entity hydration belongs entirely to
   * `src/repositories/mysql/**`.
   *
   * EVERY COLLECTION PARAMETER IS OPTIONAL AND DEFAULTS TO `[]`, and that is not a convenience: a
   * Hibernate-managed collection never handed back null, so an entity hydrated without a join must
   * present an empty array rather than `undefined` - the convention the legacy suite asserts for
   * `Brand.getProducts()` in meta/tests/unit/entity/BrandTest.cfc.
   *
   * THE `activeFlag` RESOLUTION DISTINGUISHES TWO KINDS OF ABSENCE. The ORM `default="1"` at
   * [model/entity/Promotion.cfc:L56] applies to a row that never set the column, so NO VALUE
   * SUPPLIED must read TRUE - the answer a freshly-created CFML entity gives. A genuinely SQL NULL
   * column is a different state and reads FALSE. `mysql2` yields `null` for SQL NULL and never
   * `undefined`, so the two cases cannot collide, and `exactOptionalPropertyTypes` keeps the
   * distinction expressible. Both paths run through the SAME coercion helper, so the default is
   * coerced exactly as the legacy engine coerced it rather than being short-circuited by a
   * hand-written `true`.
   */
  constructor(init: {
    readonly promotionID: string;
    readonly promotionName?: string | undefined;
    readonly promotionSummary?: string | undefined;
    readonly promotionDescription?: string | undefined;
    readonly activeFlag?: PersistedBooleanColumn | undefined;
    readonly defaultImageID?: string | undefined;
    readonly promotionPeriods?: PromotionPeriod[] | undefined;
    readonly promotionCodes?: PromotionCode[] | undefined;
    readonly appliedPromotions?: PromotionApplied[] | undefined;
    readonly remoteID?: string | undefined;
    readonly createdDateTime?: Date | undefined;
    readonly createdByAccountID?: string | undefined;
    readonly modifiedDateTime?: Date | undefined;
    readonly modifiedByAccountID?: string | undefined;
  }) {
    this.promotionID = init.promotionID;
    this.promotionName = init.promotionName;
    this.promotionSummary = init.promotionSummary;
    this.promotionDescription = init.promotionDescription;
    this.activeFlag = cfBoolean(
      init.activeFlag === undefined ? ACTIVE_FLAG_ORM_DEFAULT : init.activeFlag,
    );
    this.defaultImageID = init.defaultImageID;
    this.promotionPeriods = init.promotionPeriods ?? [];
    this.promotionCodes = init.promotionCodes ?? [];
    this.appliedPromotions = init.appliedPromotions ?? [];
    this.remoteID = init.remoteID;
    this.createdDateTime = init.createdDateTime;
    this.createdByAccountID = init.createdByAccountID;
    this.modifiedDateTime = init.modifiedDateTime;
    this.modifiedByAccountID = init.modifiedByAccountID;
  }

  // ============
  // START: Persistent Property Accessors
  // ====================
  // None of these has a hand-written legacy body: `accessors="true"` on the intermediate
  // model/entity/HibachiEntity.cfc generates one per declared property. They are authored here with
  // the legacy names VERBATIM because interface parity is the acceptance contract - a reviewer
  // diffs this surface against the CFC member by member, and renaming any of them to something more
  // idiomatic would destroy exactly the property that makes the port checkable.

  /** [model/entity/Promotion.cfc:L52] The `SwPromotion` primary key. `''` on an unsaved row. */
  getPromotionID(): string {
    return this.promotionID;
  }

  /**
   * [model/entity/Promotion.cfc:L53]
   *
   * RETURNS `string | undefined`, AND THE `| undefined` IS NOT OPTIONAL. This is a PUBLISHED
   * FAR-SIDE CONTRACT - [model/entity/PromotionPeriod.cfc:L91-L93] reaches it as
   *   `return getPromotion().getPromotionName();`,
   * and [model/service/PromotionService.cfc:L403] and [model/service/PromotionService.cfc:L449] as
   * `reward.getPromotionPeriod().getPromotion().getPromotionName()` - so the return type is a
   * cross-module decision.
   *
   * `''` IS NOT SUBSTITUTED FOR AN UNSET NAME. The column is nullable: L53 reads
   *   `property name="promotionName" ormtype="string";`
   * with NO `notnull="true"`, unlike [model/entity/Product.cfc:L55]; requiredness comes only from
   * model/validation/Promotion.json in the `save` context, which says nothing about a row already
   * in the table. And returning `''` would SILENTLY REPAIR A PRESERVED DEFECT: `promotionPeriod.ts`
   * consumes this accessor as `string | undefined` inside `getSimpleRepresentation()` and RAISES
   * when it is absent, reproducing the CFML return-type coercion failure that
   * [model/entity/PromotionPeriod.cfc:L91]'s `returntype="string"` produces on a null name. A
   * promotion without a name is a data defect for callers in `src/services/**` to reject, not a
   * value for this accessor to fabricate.
   */
  getPromotionName(): string | undefined {
    return this.promotionName;
  }

  /** [model/entity/Promotion.cfc:L54] `length="1000"` recorded, not enforced. */
  getPromotionSummary(): string | undefined {
    return this.promotionSummary;
  }

  /** [model/entity/Promotion.cfc:L55] `length="4000"` recorded, not enforced. */
  getPromotionDescription(): string | undefined {
    return this.promotionDescription;
  }

  /**
   * [model/entity/Promotion.cfc:L56] `ormtype="boolean" default="1"`.
   *
   * TOTAL, and already coerced: the single `cfBoolean()` call happens once in the constructor, so
   * repeated reads cannot disagree with each other and no raw column shape survives past hydration.
   * See the constructor for the two-kinds-of-absence rule that governs the value.
   */
  getActiveFlag(): boolean {
    return this.activeFlag;
  }

  /**
   * The `defaultImageID` FK column, opaque. [model/entity/Promotion.cfc:L59]
   *
   * This is the ONLY member authored for that association: there is deliberately no
   * `getDefaultImage()`, because `Image` is out of scope and the FK is inert. In the legacy tree
   * this accessor is not hand-written either - it resolves through the `get<XXX>ID` branch of the
   * dispatcher at [org/Hibachi/HibachiEntity.cfc:L529-L531], which returns
   * `getPropertyPrimaryID(propertyName="defaultImage")` for a many-to-one - so exposing the
   * identifier while dropping the object is faithful to what the framework itself offered.
   */
  getDefaultImageID(): string | undefined {
    return this.defaultImageID;
  }

  /** [model/entity/Promotion.cfc:L67] */
  getRemoteID(): string | undefined {
    return this.remoteID;
  }

  /** [model/entity/Promotion.cfc:L70] `hb_populateEnabled="false"`. */
  getCreatedDateTime(): Date | undefined {
    return this.createdDateTime;
  }

  /**
   * The `createdByAccountID` FK column, opaque. [model/entity/Promotion.cfc:L71] Same `get<XXX>ID`
   * provenance as `getDefaultImageID()`, and the same reason no `Account` object is exposed.
   */
  getCreatedByAccountID(): string | undefined {
    return this.createdByAccountID;
  }

  /** [model/entity/Promotion.cfc:L72] `hb_populateEnabled="false"`. */
  getModifiedDateTime(): Date | undefined {
    return this.modifiedDateTime;
  }

  /** The `modifiedByAccountID` FK column, opaque. [model/entity/Promotion.cfc:L73] */
  getModifiedByAccountID(): string | undefined {
    return this.modifiedByAccountID;
  }

  // ============
  // END:  Persistent Property Accessors
  // ====================

  // ============
  // Collection Accessors
  // ============================================================
  // LEGACY-NOTE [model/entity/Promotion.cfc:L141-L164]: ALL THREE ACCESSORS RETURN THE LIVE
  // INTERNAL ARRAY, and that is forced by the structure of this component rather than chosen. Every
  // one of the six bidirectional helpers at L141-L164 is a PURE FAR-SIDE DELEGATION - not one
  // touches `variables.promotionPeriods`, `variables.promotionCodes` or
  // `variables.appliedPromotions` - so EVERY near-side array mutation in this aggregate is
  // performed by the child, reaching back in THROUGH these accessors:
  //
  //   getPromotionPeriods()  <- PromotionPeriod.cfc:L101 arrayAppend; L108 arrayFind and L110
  //                             arrayDeleteAt on the reachable found path
  //   getPromotionCodes()    <- PromotionCode.cfc:L105 arrayAppend; L116 arrayDeleteAt
  //   getAppliedPromotions() <- PromotionApplied.cfc:L82 arrayAppend; L91 arrayDeleteAt
  //
  // A defensive copy on any of the three would make all six helpers silent no-ops with respect to
  // this entity's own state and let the two halves of the graph drift apart with no error anywhere.
  // The return types are therefore the mutable `T[]` and NOT `readonly T[]`, so the contract is
  // visible in the type. Contrast collections that sibling modules correctly expose as `readonly`,
  // `PromotionCode.getAccounts()` among them, where the ownership census finds no far-side
  // mutation.

  /** [model/entity/Promotion.cfc:L62] The LIVE array. See the note above before changing this. */
  getPromotionPeriods(): PromotionPeriod[] {
    return this.promotionPeriods;
  }

  /**
   * [model/entity/Promotion.cfc:L63] The LIVE array. Also read internally by `getCurrentFlag()`
   * [L86], `getCurrentPromotionCodeFlag()` [L112] and `getPromotionCodesDeletableFlag()` [L126].
   */
  getPromotionCodes(): PromotionCode[] {
    return this.promotionCodes;
  }

  /**
   * [model/entity/Promotion.cfc:L64] The LIVE array. Also read internally by `isDeletable()`
   * [L171], which is why its emptiness is load-bearing rather than incidental.
   */
  getAppliedPromotions(): PromotionApplied[] {
    return this.appliedPromotions;
  }

  // ============
  // END:  Collection Accessors
  // =============================

  // ============
  // Containment Probes
  // ==============================================================
  // None of the three is declared in model/entity/Promotion.cfc, and all three are nonetheless
  // MANDATORY here, because each is called across a module boundary by the child that owns the
  // foreign key: [model/entity/PromotionPeriod.cfc:L100], [model/entity/PromotionCode.cfc:L104] and
  // [model/entity/PromotionApplied.cfc:L81] each guard with
  //   `!arguments.promotion.has<Child>( this )`.
  //
  // WHERE THEY COME FROM. Each is generated by the CFML ORM for a collection declared with
  // `singularname` - L62, L63 and L64 respectively - which is why all three RESOLVE AND DO NOT
  // THROW. They are NOT products of the `onMissingMethod` dispatcher at
  // [org/Hibachi/HibachiEntity.cfc:L507-L565], which has no singular `has<Property>` branch and so
  // terminates in the throw at [L565] - the fate of `hasPromotionAccount`, and the reason this
  // class must never declare a `promotionAccounts` collection.
  //
  // THE COMPARISON BASIS IS THE PRIMARY KEY, never deep equality and never object reference.
  // Reference identity is consulted only when the candidate's key is the `unsavedvalue=""`
  // sentinel, where no primary key exists and Hibernate itself falls back to instance identity for
  // a transient row; a pure key comparison would report two DIFFERENT unsaved children as the same
  // row and make the far side skip a legitimate append. The fallback is unreachable from all three
  // legacy call sites, each guarding as `isNew() or !has<Child>( this )`.
  //
  // ALL THREE RETURN `false` ON AN EMPTY ARRAY. At the [model/entity/PromotionCode.cfc:L104] site
  // that `false` is negated to `true` and an append occurs, which is PERMISSIVE and correct.
  //
  // ON ARRAY INDEX BASE: `.some(...)` avoids the 1-based CFML `arrayFind` convention entirely;
  // where an index IS needed the gate is `findIndex(...) !== -1`, never `> 0`.

  /** Containment probe for `promotionPeriods` [model/entity/Promotion.cfc:L62]. PK basis. */
  hasPromotionPeriod(promotionPeriod: PromotionPeriod): boolean {
    const candidateID: string = promotionPeriod.getPromotionPeriodID();
    if (candidateID === '') {
      return this.promotionPeriods.includes(promotionPeriod);
    }
    return this.promotionPeriods.some(
      (held: PromotionPeriod) => held.getPromotionPeriodID() === candidateID,
    );
  }

  /** Containment probe for `promotionCodes` [model/entity/Promotion.cfc:L63]. PK basis. */
  hasPromotionCode(promotionCode: PromotionCode): boolean {
    const candidateID: string = promotionCode.getPromotionCodeID();
    if (candidateID === '') {
      return this.promotionCodes.includes(promotionCode);
    }
    return this.promotionCodes.some(
      (held: PromotionCode) => held.getPromotionCodeID() === candidateID,
    );
  }

  /** Containment probe for `appliedPromotions` [model/entity/Promotion.cfc:L64]. PK basis. */
  hasAppliedPromotion(promotionApplied: PromotionApplied): boolean {
    const candidateID: string = promotionApplied.getPromotionAppliedID();
    if (candidateID === '') {
      return this.appliedPromotions.includes(promotionApplied);
    }
    return this.appliedPromotions.some(
      (held: PromotionApplied) => held.getPromotionAppliedID() === candidateID,
    );
  }

  // ============
  // END:  Containment Probes
  // ===============================

  // ============
  // Non-Persistent Property Methods [model/entity/Promotion.cfc:L81-L136]
  // ===========
  //
  // ONE STRUCTURAL NOTE APPLYING TO ALL FOUR. The legacy guard is
  //   `if(!structKeyExists(variables, "<name>"))`,
  // which tests KEY PRESENCE and not truthiness, so the faithful equivalent is
  //   `if (this.<field> === undefined)`:
  // these memos hold a `boolean`, and a computed `false` is a legitimate memoized answer that must
  // not re-trigger the computation. `if (!this.<field>)` would recompute forever after a `false`
  // result. This is also why `src/lib/cfml/struct.ts` is NOT imported - those four
  // `structKeyExists` calls are memo guards on PRIVATE STATE, not case-insensitive lookups on
  // domain data - and why `isNullish` is not used: the legacy guard is `structKeyExists`, not
  // `isNull`.
  //
  // A SECOND NOTE, ON HOW THE COLLECTIONS ARE READ INTERNALLY. The legacy bodies reach their own
  // collections through the generated accessor (L86, L112, L126, L98, L171) whereas the bodies
  // below read the private field directly. The two are INDISTINGUISHABLE here: each accessor is an
  // identity return of exactly that field, handing back the same live array reference rather than a
  // copy, so a field read and an accessor read observe the same object and the same far-side
  // mutations. The accessors remain the sole route for CROSS-module reads, which is what the
  // far-side contracts depend on.
  //
  // LEGACY-NOTE [model/entity/Promotion.cfc:L83-L121]: THE FIRST THREE MEMOS ARE CORRECT, AND THAT
  // IS THE EVIDENCE THAT THE FOURTH IS A DEFECT. In `getCurrentFlag`,
  // `getCurrentPromotionPeriodFlag` and `getCurrentPromotionCodeFlag` the guard key, the write key
  // and the return key are the same identifier, so no defect marker is attached to any of them.
  // Together with the equally correct memos at [model/entity/PromotionPeriod.cfc:L138-L145] and
  // [model/entity/PromotionCode.cfc:L86-L93] they are the CONTROL CASES proving the four-way
  // mismatch in `getPromotionCodesDeletableFlag()` is a copy-paste defect and not a house idiom.

  /**
   * `getCurrentFlag` - is this promotion currently in force? [model/entity/Promotion.cfc:L83-L92]
   *
   * The legacy body, verbatim:
   *
   *   variables.currentFlag = false;
   *   if( getCurrentPromotionPeriodFlag() && ( !arrayLen(getPromotionCodes()) ||
   *   getCurrentPromotionCodeFlag() ) ) {
   *     variables.currentFlag = true;
   *   }
   *
   * THREE SEMANTIC POINTS, ALL PRESERVED DELIBERATELY.
   *
   *   1. THE SEED POLARITY IS `false`, NARROWED TO `true` - the OPPOSITE of
   *      `PromotionPeriod.getCurrentFlag()` and `PromotionCode.getCurrentFlag()`, which each seed
   *      `true` and narrow to `false`. The seed is written BEFORE the condition, exactly as at L85
   *      versus L86.
   *   2. THE CODE TEST IS PERMISSIVE ON AN EMPTY COLLECTION. `!arrayLen(getPromotionCodes())` means
   *      a
   *      promotion with NO codes is current purely on the strength of its periods - a code is a
   *      RESTRICTION, not a requirement. Collapsing it into the restrictive reading would stop
   *      every
   *      codeless promotion from applying, which is a money bug. Contrast
   *      `getCurrentPromotionPeriodFlag()` immediately below, which is RESTRICTIVE on ITS empty
   *      collection - two opposite conventions in one file, never unified behind a shared helper.
   *   3. `&&` AND `||` SHORT-CIRCUIT IN CFML EXACTLY AS IN TYPESCRIPT, so the operand order is
   *      preserved verbatim: `getCurrentPromotionCodeFlag()` is not evaluated when the code
   *      collection
   *      is empty, and neither code-side term is evaluated when no period is current. Both callees
   *      are
   *      memoized, so the ordering is observable through which memos get populated.
   */
  getCurrentFlag(): boolean {
    if (this.currentFlag === undefined) {
      // [model/entity/Promotion.cfc:L85] - the seed, written before the test.
      this.currentFlag = false;
      // [model/entity/Promotion.cfc:L86] - operand order and short-circuit preserved verbatim.
      if (
        this.getCurrentPromotionPeriodFlag() &&
        (this.promotionCodes.length === 0 || this.getCurrentPromotionCodeFlag())
      ) {
        this.currentFlag = true;
      }
    }

    return this.currentFlag;
  }

  /**
   * `getCurrentPromotionPeriodFlag` - does ANY of this promotion's periods currently apply?
   * [model/entity/Promotion.cfc:L95-L107]
   *
   * LEGACY-NOTE [model/entity/Promotion.cfc:L98-L103]: the legacy loop is an indexed `for` from 1
   * to `arrayLen(getPromotionPeriods())` that flips the flag and `break`s on the first current
   * period. `Array.prototype.some` is the exact equivalent - same first-match-wins short-circuit,
   * same `false` for an empty array - and removes the 1-based/0-based translation risk entirely
   * rather than merely handling it. The legacy re-evaluates `arrayLen(...)` every iteration;
   * `.some()` does not, which is an efficiency difference and not a behavioural one.
   *
   * EMPTY `promotionPeriods` YIELDS `false` - RESTRICTIVE. Contrast point 2 on `getCurrentFlag()`
   * above, whose empty-collection test in the very same file is PERMISSIVE.
   *
   * `PromotionPeriod.getCurrentFlag()` IS CALLED WITH NO ARGUMENT, its legacy arity at
   * [model/entity/PromotionPeriod.cfc:L137] and the arity the sibling keeps, with the clock
   * injected into that entity's own constructor. The project's single entity-layer signature
   * widening was spent on `PromotionPeriod.isCurrent(now)`, which this call path does not use.
   */
  getCurrentPromotionPeriodFlag(): boolean {
    if (this.currentPromotionPeriodFlag === undefined) {
      this.currentPromotionPeriodFlag = this.promotionPeriods.some((period: PromotionPeriod) =>
        period.getCurrentFlag(),
      );
    }

    return this.currentPromotionPeriodFlag;
  }

  /**
   * `getCurrentPromotionCodeFlag` - does ANY of this promotion's codes currently apply?
   * [model/entity/Promotion.cfc:L109-L121]
   *
   * Structurally identical to `getCurrentPromotionPeriodFlag()` above, over `promotionCodes` and
   * `PromotionCode.getCurrentFlag()`, which is likewise ZERO-ARG at
   * [model/entity/PromotionCode.cfc:L85]. EMPTY `promotionCodes` YIELDS `false` - RESTRICTIVE.
   *
   * That is not a contradiction of `getCurrentFlag()`'s permissive empty-codes gate: THIS method
   * asks "is some code current?", whose honest answer for no codes is no, while the CALLER asks "do
   * the codes restrict this promotion?", whose honest answer for no codes is also no - which is why
   * L86 tests emptiness FIRST and short-circuits past this method rather than relying on its
   * answer.
   */
  getCurrentPromotionCodeFlag(): boolean {
    if (this.currentPromotionCodeFlag === undefined) {
      this.currentPromotionCodeFlag = this.promotionCodes.some((code: PromotionCode) =>
        code.getCurrentFlag(),
      );
    }

    return this.currentPromotionCodeFlag;
  }

  // LEGACY-DEFECT [model/entity/Promotion.cfc:L124-L133]: four-way key mismatch - declared property
  // `promotionCodesDeletableFlag` (L79), guard key `promotionCodeDeletableFlag` (L124),
  // write/return key `promotionCodeDeleteableFlag` (L125/L128/L133). The guard key is never
  // written, so the memo is permanently ineffective - though the returned value is always correct.
  // Preserved deliberately; do not fix without a product decision.
  //
  //   | # | identifier                  | role              | locator       | spelling           |
  //   | 1 | promotionCodesDeletableFlag | declared property | L79           | plural, correct    |
  //   | 2 | promotionCodeDeletableFlag  | the memo GUARD    | L124          | singular, correct  |
  //   | 3 | promotionCodeDeleteableFlag | the WRITES        | L125 and L128 | singular, misspelt |
  //   | 4 | promotionCodeDeleteableFlag | the RETURN        | L133          | same as #3         |
  //
  // Because the write (#3) and the return (#4) agree, THE RETURNED VALUE IS ALWAYS CORRECT: the
  // defect costs redundant computation, never a wrong answer. The declared name (#1) matches
  // neither, so the framework's generated accessor would consult a fifth, permanently empty key.
  //
  // LEGACY-NOTE [model/entity/Promotion.cfc:L124-L133]: THE MEMO IS DELIBERATELY OMITTED IN
  // TYPESCRIPT, and that is faithful reproduction rather than a divergence. The legacy recomputes
  // on every call, so computing freshly on every call reproduces the observable behaviour exactly.
  // Memoizing under a single consistent key would be the silent repair: it would change how many
  // times `PromotionCode.isDeletable()` is invoked, and that count IS observable, since
  // `isDeletable()` is a delete-context validation over a collection that can change between two
  // calls. There is therefore no backing field for L79 on this class. The three CORRECT memos above
  // are the control cases that make this omission legible rather than arbitrary.

  /**
   * `getPromotionCodesDeletableFlag` - are ALL of this promotion's codes deletable?
   * [model/entity/Promotion.cfc:L123-L134]
   *
   * The legacy body starts from `true` and flips to `false` on the first non-deletable code, with a
   * `break`. `for(var promotionCode in getPromotionCodes())` iterates ELEMENTS in modern CFML, so
   * `Array.prototype.every` is the exact equivalent: same accumulation, same short-circuit, same
   * empty-array result.
   *
   * EMPTY `promotionCodes` YIELDS `true` - PERMISSIVE. The third distinct empty-collection semantic
   * in this one file, alongside the permissive gate at L86 and the restrictive evaluators at L98
   * and L112, and none of the three is unified with the others.
   *
   * THE NAME IS VERBATIM, INCLUDING THE PLURAL "Codes", because this method sits on a live
   * delete-context validation path: model/validation/Promotion.json declares
   *   `"promotionCodes": [{"contexts":"delete","method":"getPromotionCodesDeletableFlag"}]`,
   * so the validator resolves it BY NAME. Enforcement of the rule itself is a service-tier concern.
   *
   * NOT MEMOIZED - see the marker and note above. Two calls perform two full evaluations.
   *
   * @throws Error when a promotion code does not carry the framework-inherited `isDeletable()`. See
   *   {@link FrameworkDeletableEntity}. The raise cannot occur for an empty collection, because
   *   `.every()` never probes.
   */
  getPromotionCodesDeletableFlag(): boolean {
    return this.promotionCodes.every((promotionCode: PromotionCode): boolean => {
      if (!reachesFrameworkIsDeletable(promotionCode)) {
        throw new Error(
          'Promotion.getPromotionCodesDeletableFlag cannot evaluate a promotion code: ' +
            'model/entity/Promotion.cfc:L127 calls promotionCode.isDeletable(), which is NOT ' +
            'declared on model/entity/PromotionCode.cfc and resolves in the legacy tree to the ' +
            'framework base at org/Hibachi/HibachiEntity.cfc:L204-L206, whose body is ' +
            '!getService("hibachiValidationService").validate(object=this, context="delete", ' +
            'setErrors=false).hasErrors(). That base class is deliberately not ported, so the ' +
            'member is absent on this promotion code. No boolean is substituted: both answers are ' +
            'load-bearing on a delete path, true would report a promotion as deletable while its ' +
            'codes are still attached to live orders - the exact outcome ' +
            'model/validation/PromotionCode.json\'s {"contexts":"delete","maxCollection":0} rule ' +
            'exists to prevent - and false would block a legitimate deletion permanently. The fix ' +
            'is to declare isDeletable(): boolean on src/domain/entities/promotionCode.ts as that ' +
            'delete-context rule over its already-materialized getOrders() collection.',
        );
      }

      // [model/entity/Promotion.cfc:L127] - the member is called exactly as the legacy calls it.
      return promotionCode.isDeletable();
    });
  }

  // ============
  // END:  Non-Persistent Property Methods
  // ==================

  // =============
  // Bidirectional Helper Methods [model/entity/Promotion.cfc:L138-L166]
  // ============
  //
  // THE STRUCTURAL HEADLINE, AND THE REASON THE THREE COLLECTION ACCESSORS RETURN THE LIVE ARRAY.
  // Not one of these six helpers touches `variables.promotionPeriods`, `variables.promotionCodes`
  // or `variables.appliedPromotions`. Every one PURELY DELEGATES to the far side's `setPromotion`
  // or `removePromotion`, and every near-side array mutation is performed BY the far side through
  // the accessor:
  //
  //   addPromotionPeriod     arrayAppend   [model/entity/PromotionPeriod.cfc:L101]
  //   addPromotionCode       arrayAppend   [model/entity/PromotionCode.cfc:L105]
  //   addAppliedPromotion    arrayAppend   [model/entity/PromotionApplied.cfc:L82]
  //   removePromotionCode    arrayDeleteAt [model/entity/PromotionCode.cfc:L116]
  //   removeAppliedPromotion arrayDeleteAt [model/entity/PromotionApplied.cfc:L91]
  //
  // A DEFENSIVE COPY IN ANY OF THE THREE ACCESSORS WOULD MAKE ALL SIX HELPERS A SILENT NO-OP with
  // respect to this entity's own state, which is why they are typed `T[]` and not `readonly T[]`.
  //
  // LEGACY-NOTE [model/entity/Promotion.cfc:L141-L145]: the period helpers declare and use a
  // capital-P argument name - `required any PromotionPeriod` at L141/L144, then
  // `arguments.PromotionPeriod.setPromotion( this )` at L142/L145. Internally consistent but
  // non-conventional, and a different wart from [model/entity/PromotionCode.cfc:L105] where the
  // DECLARATION is lowercase and only the USE is capitalised. CFML argument names are
  // case-insensitive, so neither changes behaviour; TypeScript parameter names are lowercase.
  //
  // LEGACY-NOTE [model/entity/PromotionCode.cfc:L109-L120]: `PromotionCode.removePromotion` IS
  // CORRECT, and that is what proves the other two are defects. Its L116 reads
  // `arrayDeleteAt(arguments.promotion.getPromotionCodes(), index)` - the DECLARED argument - while
  // [model/entity/PromotionPeriod.cfc:L110] and [model/entity/PromotionAccount.cfc:L103] both read
  // `arguments.account...` in a method whose only declared argument is `promotion`. Three
  // near-identical methods, one right and two wrong, is copy-paste damage rather than a CFML idiom.

  /**
   * `addPromotionPeriod` - attach a period to this promotion.
   * [model/entity/Promotion.cfc:L141-L143]
   *
   *   arguments.PromotionPeriod.setPromotion( this );
   *
   * A pure far-side delegation, exactly as written. The near side is mutated by
   * `PromotionPeriod.setPromotion` [model/entity/PromotionPeriod.cfc:L98-L103], which is SOUND: it
   * guards on `isNew() or !arguments.promotion.hasPromotionPeriod(this)` at L100 and appends to
   * `arguments.promotion.getPromotionPeriods()` at L101. So this helper WORKS.
   *
   * No `isNew()` guard is authored on THIS side, because the legacy has none here: the guard lives
   * entirely in the callee and reads the CHILD's newness, never the parent's. Adding one would
   * change behaviour.
   */
  addPromotionPeriod(promotionPeriod: PromotionPeriod): void {
    promotionPeriod.setPromotion(this);
  }

  // LEGACY-DEFECT [model/entity/PromotionPeriod.cfc:L110]: the delegated-to `removePromotion`
  // references the undeclared `arguments.account`, so this always throws and can never remove a
  // period.
  //
  // Preserved deliberately; do not fix without a product decision.
  //
  // THE MECHANISM, because the throw originates in another file. `PromotionPeriod.removePromotion`
  // is declared at [model/entity/PromotionPeriod.cfc:L104]; its body computes
  //   `var index = arrayFind(arguments.promotion.getPromotionPeriods(), this)`
  // at L108, and when that FIND SUCCEEDS it reaches
  // `arrayDeleteAt(arguments.account.getPromotionPeriods(), index)` at L110. `account` is not a
  // declared argument, so the expression is unresolvable and the call raises. The find succeeding
  // is the NORMAL case - exactly the case in which a caller wants a removal - so
  // `Promotion.removePromotionPeriod()` can never successfully remove anything, and the
  // `structDelete(variables,"promotion")` at L112 is unreachable on the found path.
  //
  // Preserved by delegating exactly as the legacy does, so the throw propagates out of
  // `promotionPeriod.ts`. No second independent throw is added here, nothing is caught or guarded,
  // and no near-side array is touched - because the legacy touches none. The return type stays
  // `void` rather than `never`: the legacy declares `public void function` and the raise originates
  // in the callee.

  /**
   * `removePromotionPeriod` - detach a period from this promotion.
   * [model/entity/Promotion.cfc:L144-L146]
   *
   *   arguments.PromotionPeriod.removePromotion( this );
   *
   * @throws Error propagated from `PromotionPeriod.removePromotion` - see the marker above. This is
   *   the preserved legacy behaviour, not a port defect.
   */
  removePromotionPeriod(promotionPeriod: PromotionPeriod): void {
    promotionPeriod.removePromotion(this);
  }

  /**
   * `addPromotionCode` - attach a code to this promotion. [model/entity/Promotion.cfc:L149-L151]
   *
   *   arguments.promotionCode.setPromotion(this);
   *
   * A pure far-side delegation. `PromotionCode.setPromotion`
   * [model/entity/PromotionCode.cfc:L101-L107] is SOUND - it guards on
   *   `isNew() or !arguments.promotion.hasPromotionCode(this)`
   * at L104 and appends to `arguments.Promotion.getPromotionCodes()` at L105 - so this helper
   * WORKS. No defect marker.
   */
  addPromotionCode(promotionCode: PromotionCode): void {
    promotionCode.setPromotion(this);
  }

  /**
   * `removePromotionCode` - detach a code from this promotion.
   * [model/entity/Promotion.cfc:L153-L155]
   *
   *   arguments.promotionCode.removePromotion(this);
   *
   * A pure far-side delegation, and THIS ONE WORKS: `PromotionCode.removePromotion`
   * [model/entity/PromotionCode.cfc:L109-L120] is CORRECT, using the declared `arguments.promotion`
   * at L116. NO DEFECT MARKER - see the note above the block for why its correctness is the
   * evidence against its two broken siblings.
   */
  removePromotionCode(promotionCode: PromotionCode): void {
    promotionCode.removePromotion(this);
  }

  /**
   * `addAppliedPromotion` - record an application of this promotion.
   * [model/entity/Promotion.cfc:L158-L160]
   *
   *   arguments.promotionApplied.setPromotion(this);
   *
   * A pure far-side delegation. `PromotionApplied.setPromotion`
   * [model/entity/PromotionApplied.cfc:L79-L83] is SOUND - it guards on
   *   `isNew() or !arguments.promotion.hasAppliedPromotion( this )`
   * at L81 and appends to `arguments.promotion.getAppliedPromotions()` at L82 - so this helper
   * WORKS. No defect marker.
   */
  addAppliedPromotion(promotionApplied: PromotionApplied): void {
    promotionApplied.setPromotion(this);
  }

  /**
   * `removeAppliedPromotion` - drop a recorded application of this promotion.
   * [model/entity/Promotion.cfc:L162-L164]
   *
   *   arguments.promotionApplied.removePromotion(this);
   *
   * A pure far-side delegation, and THIS ONE WORKS TOO: `PromotionApplied.removePromotion`
   * [model/entity/PromotionApplied.cfc:L85-L94] is clean, verified free of the `arguments.account`
   * leak and of any add/remove inversion, using the declared `arguments.promotion` at L91. No
   * defect marker.
   */
  removeAppliedPromotion(promotionApplied: PromotionApplied): void {
    promotionApplied.removePromotion(this);
  }

  // THE "remove-that-ADDs" INVERSION CROSS-CHECK: ZERO INVERSIONS IN model/entity/Promotion.cfc.
  // The inversion class is real - [model/entity/Option.cfc:L129-L131] and
  // [model/entity/Option.cfc:L145-L147] each declare a `remove*` that calls
  // `addExcludedOption(this)`, which is why the check is performed rather than assumed. Here every
  // `remove*` (L144, L153, L162) delegates to a `removePromotion` and every `add*` to a
  // `setPromotion`.
  //
  // THE VERDICT IS ABOUT DELEGATION DIRECTION, NOT OUTCOME: `removePromotionPeriod` is clean here -
  // it correctly calls a `remove*` - and SEPARATELY always throws, because the callee it correctly
  // calls is itself broken at [model/entity/PromotionPeriod.cfc:L110].

  // =============
  // END:  Bidirectional Helper Methods
  // ====================

  // ==================
  // START: Overridden Methods
  // =========================
  // [model/entity/Promotion.cfc:L168] opens this block and L174 closes it. Exactly one member.

  /**
   * `isDeletable` - may this promotion be deleted? [model/entity/Promotion.cfc:L170-L172]
   *
   *   return arrayLen( getAppliedPromotions() ) == 0;
   *
   * AN OVERRIDE IN THE LEGACY, proved by its placement under the "Overridden Methods" banner. The
   * base at [org/Hibachi/HibachiEntity.cfc:L204-L206] runs generic delete-context validation; this
   * entity replaces it with one concrete predicate faithful to the declarative rule it stands in
   * for - model/validation/Promotion.json declares
   *   `"appliedPromotions": [{"contexts":"delete","maxCollection":0}]`,
   * which is exactly `arrayLen(...) == 0`. No `override` modifier is emitted: `noImplicitOverride`
   * only applies where a TypeScript base class exists.
   *
   * EMPTY `appliedPromotions` YIELDS `true` - PERMISSIVE. The fifth and last empty-collection site
   * in this file (L86 permissive, L98 restrictive, L112 restrictive, L126 permissive, L171
   * permissive). No shared helper is extracted across them even though three reduce to the same
   * expression, because collapsing an empty-collection convention is a money bug.
   *
   * Reads through the LIVE collection, so it observes far-side mutations - including one made after
   * a previous call. There is no memo here in the legacy and none is added. Three shipped siblings
   * consume this member, mirroring `getPromotionPeriod().getPromotion().isDeletable()`.
   */
  isDeletable(): boolean {
    return this.appliedPromotions.length === 0;
  }

  // ==================
  // END:  Overridden Methods
  // =========================

  // ===================
  // ORM Event Hooks [model/entity/Promotion.cfc:L176-L178]
  // ===================
  // COMPLETELY EMPTY in the source, so nothing is authored: no `preInsert`, no `preUpdate`, no path
  // maintenance, no UUID seeding. See the ORM-hooks LEGACY-NOTE in the header.
}

// (end of Promotion entity)
