/**
 * Statement-shape tests for `MysqlPromotionRepository.saveRoundingRule`.
 *
 * ****************************************************************************
 * ** WHY THIS FILE IS NARROW, AND WHY IT EXISTS AT ALL.                     **
 * **                                                                        **
 * ** It covers ONE method. `mysqlPromotionRepository.ts` has no integration  **
 * ** suite of its own - the folder holds one per adapter for the other five,  **
 * ** and the promotion adapter's reads are covered through the engine suites  **
 * ** that consume them. Rather than open a suite for the whole adapter as a   **
 * ** side effect of adding a write, this file is scoped to the write, and     **
 * ** named for it, so its scope is legible from the filename.                **
 * **                                                                        **
 * ** The method it covers is the `super.save(argumentcollection=arguments)`   **
 * ** half of `saveRoundingRule` [model/service/RoundingRuleService.cfc:L63]   **
 * ** that the target had dropped. It needs SQL-level coverage specifically    **
 * ** because there is NO HAND-WRITTEN LEGACY QUERY to diff against: the       **
 * ** statement was generated by Hibernate from the entity's persistent-       **
 * ** property metadata [model/entity/RoundingRule.cfc:L52-L61]. When no       **
 * ** legacy statement exists to compare with, the emitted statement itself    **
 * ** is the only artifact a reviewer can check, so it is pinned here.         **
 * **                                                                        **
 * ** NET-NEW COVERAGE. `meta/tests/unit/dao/` holds only AccountDAOTest and   **
 * ** PaymentDAOTest, and there is no legacy RoundingRuleDAOTest, so nothing    **
 * ** here traces to a legacy antecedent (AAP 0.6.6).                          **
 * ****************************************************************************
 *
 * The four properties worth pinning:
 *
 *   1. INSERT AGAINST UPDATE REPRODUCES HIBERNATE'S DETACHED-ENTITY RECONCILIATION.
 *      A rule with no identifier is inserted under a minted one. A rule that CARRIES
 *      an identifier is probed first, then inserted if no row answers and updated if
 *      one does - because that is what the ORM behind `super.save` did, and trusting
 *      `isNew()` alone would update zero rows and report success.
 *   2. AN UPDATE NEVER REWRITES `createdDateTime`. It is
 *      `hb_populateEnabled="false"` [model/entity/RoundingRule.cfc:L58] and
 *      describes when the row appeared; rewriting it destroys audit history.
 *   3. AN ABSENT COLUMN BINDS `null`, NOT `''`. The columns are nullable
 *      [model/entity/RoundingRule.cfc:L53-L55], and an empty string would later be
 *      handed to `roundValue` as a rounding expression.
 *   4. THE WRITE IS ONE STATEMENT, so it opens no transaction. Wrapping a single
 *      atomic statement would be cargo cult.
 */

import { describe, expect, it } from 'vitest';

import { RoundingRule } from '../../../src/domain/entities/roundingRule.js';
import type { Money } from '../../../src/domain/valueObjects/money.js';
import { MysqlPromotionRepository } from '../../../src/repositories/mysql/mysqlPromotionRepository.js';
import type {
  PreparedStatementExecutor,
  SqlMutationResult,
  SqlRow,
} from '../../../src/repositories/mysql/connection.js';

// ---------------------------------------------------------------------------
// Doubles
// ---------------------------------------------------------------------------

/** One captured statement. */
interface RecordedStatement {
  readonly sql: string;
  readonly params: readonly unknown[];
  /** Whether it was issued inside `transaction`, so atomicity is provable. */
  readonly inTransaction: boolean;
}

/**
 * Records statements and answers writes with a canned affected-row count.
 *
 * `execute` answers the existence probe from `existingIdentifiers`, so a suite can
 * choose whether a row already answers to an identifier and assert which branch the
 * adapter took. Every read is recorded too, so the probe is itself assertable.
 */
class RecordingExecutor implements PreparedStatementExecutor {
  readonly mutations: RecordedStatement[] = [];
  readonly reads: RecordedStatement[] = [];
  transactionCount = 0;

  private transactionDepth = 0;

  /** Identifiers a row already answers to, so the probe can report existence. */
  constructor(private readonly existingIdentifiers: readonly string[] = []) {}

  execute(sql: string, params: readonly unknown[] = []): Promise<readonly SqlRow[]> {
    this.reads.push({ sql, params: [...params], inTransaction: this.transactionDepth > 0 });

    const probed = params[0];
    const answers = typeof probed === 'string' && this.existingIdentifiers.includes(probed);

    return Promise.resolve(answers ? [{ roundingRuleID: probed }] : []);
  }

  executeMutation(sql: string, params: readonly unknown[] = []): Promise<SqlMutationResult> {
    this.mutations.push({ sql, params: [...params], inTransaction: this.transactionDepth > 0 });

    return Promise.resolve(Object.freeze({ affectedRows: 1, warningStatus: 0 }));
  }

  async transaction<T>(work: (tx: PreparedStatementExecutor) => Promise<T>): Promise<T> {
    this.transactionCount += 1;
    this.transactionDepth += 1;

    try {
      return await work(this);
    } finally {
      this.transactionDepth -= 1;
    }
  }
}

/**
 * The rounding collaborator the hydrated entity requires.
 *
 * Raises, because persisting a rule performs no arithmetic. If the write ever
 * routed through the entity's own `roundValue` [model/entity/RoundingRule.cfc:L66-L68]
 * the run fails by name rather than silently computing something.
 */
const unreachedValueRounder = {
  roundValueByRoundingRule: (): Money => {
    throw new Error('saveRoundingRule performs no rounding arithmetic');
  },
};

/** Everything `RoundingRule`'s constructor needs, with the identity as the only required knob. */
function makeRule(
  overrides: {
    readonly roundingRuleID?: string;
    readonly roundingRuleName?: string | undefined;
    readonly roundingRuleExpression?: string | undefined;
    readonly roundingRuleDirection?: string | undefined;
    readonly createdDateTime?: Date | undefined;
    readonly modifiedDateTime?: Date | undefined;
  } = {},
): RoundingRule {
  return new RoundingRule(
    {
      roundingRuleID: overrides.roundingRuleID ?? 'rr-1',
      roundingRuleName: overrides.roundingRuleName,
      roundingRuleExpression: overrides.roundingRuleExpression,
      roundingRuleDirection: overrides.roundingRuleDirection,
      createdDateTime: overrides.createdDateTime,
      createdByAccountID: undefined,
      modifiedDateTime: overrides.modifiedDateTime,
      modifiedByAccountID: undefined,
      priceGroupRates: [],
    },
    unreachedValueRounder,
  );
}

/** Collapses whitespace so a statement can be matched without pinning its layout. */
function normalize(sql: string): string {
  return sql.replace(/\s+/g, ' ').trim();
}

function makeSubject(existingIdentifiers: readonly string[] = []): {
  subject: MysqlPromotionRepository;
  executor: RecordingExecutor;
} {
  const executor = new RecordingExecutor(existingIdentifiers);

  return { subject: new MysqlPromotionRepository(executor, unreachedValueRounder), executor };
}

/** A rule that has never been persisted: `isNew()` is `roundingRuleID === ''`. */
function makeNewRule(overrides: Parameters<typeof makeRule>[0] = {}): ReturnType<typeof makeRule> {
  return makeRule({ ...overrides, roundingRuleID: '' });
}

// ---------------------------------------------------------------------------

describe('MysqlPromotionRepository.saveRoundingRule - inserting a new rule', () => {
  it('★★ issues exactly one INSERT against SwRoundingRule, and reads nothing back', async () => {
    // PROPERTY 1. `execute` raises, so a probe query would fail the test by name.
    const { subject, executor } = makeSubject();

    await subject.saveRoundingRule(
      makeNewRule({ roundingRuleExpression: '.99', roundingRuleDirection: 'Closest' }),
    );

    expect(executor.reads).toStrictEqual([]);
    expect(executor.mutations).toHaveLength(1);
    expect(normalize(executor.mutations[0]?.sql ?? '')).toContain('INSERT INTO SwRoundingRule');
  });

  it('binds all six columns positionally, in the order the statement declares them', async () => {
    // A DETACHED rule: it carries an identifier but no row answers to it, so this is
    // the insert branch reached through the probe rather than through `isNew()`. The
    // identifier it already carries is the one written - none is minted.
    const { subject, executor } = makeSubject();

    await subject.saveRoundingRule(
      makeRule({
        roundingRuleID: 'rr-42',
        roundingRuleName: 'Nines',
        roundingRuleExpression: '.95,.99',
        roundingRuleDirection: 'Up',
      }),
    );

    expect(executor.mutations[0]?.params).toStrictEqual([
      'rr-42',
      'Nines',
      '.95,.99',
      'Up',
      expect.any(Date),
      expect.any(Date),
    ]);
  });

  it("names every column it binds, so the statement's arity matches its parameter list", async () => {
    const { subject, executor } = makeSubject();

    await subject.saveRoundingRule(makeNewRule());

    const sql = normalize(executor.mutations[0]?.sql ?? '');
    const placeholders = (sql.match(/\?/g) ?? []).length;

    expect(placeholders).toBe(executor.mutations[0]?.params.length);

    for (const column of [
      'roundingRuleID',
      'roundingRuleName',
      'roundingRuleExpression',
      'roundingRuleDirection',
      'createdDateTime',
      'modifiedDateTime',
    ]) {
      expect(sql).toContain(column);
    }
  });

  it('★ binds null, never an empty string, for an absent nullable column', async () => {
    // PROPERTY 3. `''` would be handed to `roundValue` as a rounding expression by
    // `getRoundingRuleDetailsByID` [model/service/RoundingRuleService.cfc:L73-L74].
    const { subject, executor } = makeSubject();

    await subject.saveRoundingRule(makeNewRule());

    expect(executor.mutations[0]?.params).toStrictEqual([
      expect.stringMatching(/^[0-9a-f]{32}$/),
      null,
      null,
      null,
      expect.any(Date),
      expect.any(Date),
    ]);
  });

  it('supplies both audit timestamps when the entity carries neither, from ONE captured instant', async () => {
    // Two `new Date()` reads in one statement can disagree, and an audit pair that
    // disagrees with itself is worse than one that is merely coarse.
    const { subject, executor } = makeSubject();

    await subject.saveRoundingRule(makeNewRule());

    const params = executor.mutations[0]?.params ?? [];
    const created = params[4];
    const modified = params[5];

    expect(created).toBeInstanceOf(Date);
    expect(modified).toBeInstanceOf(Date);
    expect((created as Date).getTime()).toBe((modified as Date).getTime());
  });

  it("★★ OVERWRITES the entity's own audit stamps on insert, as preInsert does", async () => {
    // CFML parity [org/Hibachi/HibachiEntity.cfc:L609-L619]: `preInsert` reads one
    // `now()` and assigns it to BOTH stamps UNCONDITIONALLY - there is no guard
    // preserving a value the entity already carried. An implementation that honoured
    // the entity's `createdDateTime` would look more considerate and would diverge.
    const { subject, executor } = makeSubject();
    const stale = new Date('2019-01-01T12:00:00.000Z');

    await subject.saveRoundingRule(
      makeNewRule({ createdDateTime: stale, modifiedDateTime: stale }),
    );

    const params = executor.mutations[0]?.params ?? [];

    expect(params[4]).not.toBe(stale);
    expect(params[5]).not.toBe(stale);
    expect((params[4] as Date).getTime()).toBe((params[5] as Date).getTime());
  });

  it('mints a 32-character hex identifier for a rule that has never been persisted', async () => {
    // `generator="uuid"` [model/entity/RoundingRule.cfc:L52] on a `length="32"` column
    // is Hibernate's undashed hex form, and the returned entity carries it - the only
    // way a caller can learn it, since the identifier is immutable.
    const { subject, executor } = makeSubject();

    const saved = await subject.saveRoundingRule(makeNewRule());

    expect(saved.getRoundingRuleID()).toMatch(/^[0-9a-f]{32}$/);
    expect(saved.isNew()).toBe(false);
    expect(executor.mutations[0]?.params[0]).toBe(saved.getRoundingRuleID());
  });

  it('probes before inserting a rule that carries an identifier, and not one that does not', async () => {
    const minted = makeSubject();

    await minted.subject.saveRoundingRule(makeNewRule());

    // `isNew()` short-circuits the probe: there is no identifier to probe with.
    expect(minted.executor.reads).toStrictEqual([]);

    const detached = makeSubject();

    await detached.subject.saveRoundingRule(makeRule({ roundingRuleID: 'rr-detached' }));

    expect(detached.executor.reads).toHaveLength(1);
    expect(detached.executor.reads[0]?.params).toStrictEqual(['rr-detached']);
  });

  it('does NOT write either account audit column, which belong to out-of-scope Account', async () => {
    // [model/entity/RoundingRule.cfc:L59, L61] are many-to-one keys into `Account`.
    // Writing an identifier this slice cannot legitimately obtain would invent data.
    const { subject, executor } = makeSubject();

    await subject.saveRoundingRule(makeNewRule());

    const sql = normalize(executor.mutations[0]?.sql ?? '');

    expect(sql).not.toContain('createdByAccountID');
    expect(sql).not.toContain('modifiedByAccountID');
  });
});

describe('MysqlPromotionRepository.saveRoundingRule - updating an existing rule', () => {
  /**
   * A rule that is not new AND whose row exists, so the probe sends it down the
   * update branch. Both halves matter: an identifier alone reaches the insert branch,
   * which is what the detached case above covers.
   */
  const existing = (): RoundingRule =>
    makeRule({
      roundingRuleID: 'rr-existing',
      roundingRuleName: 'Renamed',
      roundingRuleExpression: '0.99',
      roundingRuleDirection: 'Down',
      createdDateTime: new Date('2020-05-05T00:00:00.000Z'),
    });

  it('★★ issues an UPDATE rather than an INSERT for a rule that is not new', async () => {
    // PROPERTY 1, the other branch. Decided from `isNew()`
    // [model/service/RoundingRuleService.cfc:L57], with no probe query.
    const { subject, executor } = makeSubject(['rr-existing']);

    await subject.saveRoundingRule(existing());

    // The probe ran - that is how the branch was chosen - and produced exactly one
    // read, followed by exactly one write.
    expect(executor.reads).toHaveLength(1);
    expect(executor.mutations).toHaveLength(1);

    const sql = normalize(executor.mutations[0]?.sql ?? '');

    expect(sql).toContain('UPDATE SwRoundingRule');
    expect(sql).not.toContain('INSERT');
  });

  it('binds the three populatable columns, then modifiedDateTime, then the identifier last', async () => {
    const { subject, executor } = makeSubject(['rr-existing']);

    await subject.saveRoundingRule(existing());

    const params = executor.mutations[0]?.params ?? [];

    expect(params.slice(0, 3)).toStrictEqual(['Renamed', '0.99', 'Down']);
    expect(params[3]).toBeInstanceOf(Date);
    expect(params[4]).toBe('rr-existing');
  });

  it('★★ never rewrites createdDateTime on an update', async () => {
    // PROPERTY 2. Rewriting it would destroy the record of when the row appeared.
    const { subject, executor } = makeSubject(['rr-existing']);

    await subject.saveRoundingRule(existing());

    expect(normalize(executor.mutations[0]?.sql ?? '')).not.toContain('createdDateTime');
  });

  it('scopes the update by roundingRuleID, so one row can be affected', async () => {
    const { subject, executor } = makeSubject(['rr-existing']);

    await subject.saveRoundingRule(existing());

    expect(normalize(executor.mutations[0]?.sql ?? '')).toContain('WHERE roundingRuleID = ?');
  });

  it('writes every populatable column rather than a computed delta', async () => {
    // Hibernate flushed the whole dirty entity and the target holds no per-field
    // dirty tracking, so a subset would silently preserve a stale value.
    const { subject, executor } = makeSubject(['rr-existing']);

    await subject.saveRoundingRule(existing());

    const sql = normalize(executor.mutations[0]?.sql ?? '');

    for (const column of [
      'roundingRuleName',
      'roundingRuleExpression',
      'roundingRuleDirection',
      'modifiedDateTime',
    ]) {
      expect(sql).toContain(column);
    }
  });

  it('★ preserves createdDateTime on the RETURNED entity even though it is not written', async () => {
    // The column is absent from the SET list, so the row keeps its value - and the
    // rebuilt entity must keep reporting it rather than dropping it to undefined.
    const { subject } = makeSubject(['rr-existing']);
    const created = new Date('2020-05-05T00:00:00.000Z');

    const saved = await subject.saveRoundingRule(
      makeRule({ roundingRuleID: 'rr-existing', createdDateTime: created }),
    );

    expect(saved.getCreatedDateTime()).toBe(created);
    expect(saved.getModifiedDateTime()).toBeInstanceOf(Date);
    expect(saved.getModifiedDateTime()).not.toBe(created);
  });

  it('issues exactly one probe and one update, in that order', async () => {
    const { subject, executor } = makeSubject(['rr-existing']);

    await subject.saveRoundingRule(existing());

    expect(executor.reads).toHaveLength(1);
    expect(executor.mutations).toHaveLength(1);
    expect(normalize(executor.reads[0]?.sql ?? '')).toContain('SELECT roundingRuleID');
  });

  it('binds null for a column the entity no longer carries', async () => {
    const { subject, executor } = makeSubject(['rr-existing']);

    await subject.saveRoundingRule(makeRule({ roundingRuleID: 'rr-existing' }));

    expect((executor.mutations[0]?.params ?? []).slice(0, 3)).toStrictEqual([null, null, null]);
  });
});

describe('MysqlPromotionRepository.saveRoundingRule - contract', () => {
  it('★★ returns a NEW instance carrying what was written, not the argument', async () => {
    // The identifier and both audit stamps are immutable on the entity, so a rule that
    // arrived without an identifier cannot be told the minted one by mutation. Handing
    // back the argument would mean returning an object whose identifier is still `''`
    // after a successful insert - which is exactly how a caller loses the new row.
    const { subject } = makeSubject();
    const rule = makeNewRule({ roundingRuleExpression: '.99', roundingRuleDirection: 'Up' });

    const saved = await subject.saveRoundingRule(rule);

    expect(saved).not.toBe(rule);
    expect(rule.getRoundingRuleID()).toBe('');
    expect(saved.getRoundingRuleID()).toMatch(/^[0-9a-f]{32}$/);

    // Every unwritten field is carried across unchanged.
    expect(saved.getRoundingRuleExpression()).toBe('.99');
    expect(saved.getRoundingRuleDirection()).toBe('Up');
  });

  it('★ opens no transaction, because one statement is already atomic', async () => {
    // PROPERTY 4. Wrapping a single statement would be cargo cult; `transaction` is
    // for the multi-statement cascades where a half-application is possible.
    const { subject, executor } = makeSubject();

    await subject.saveRoundingRule(makeRule());
    await subject.saveRoundingRule(makeRule({ roundingRuleID: 'rr-2' }));

    expect(executor.transactionCount).toBe(0);
    expect(executor.mutations.every((statement) => !statement.inTransaction)).toBe(true);
  });

  it('participates in a caller-owned transaction when constructed over a tx executor', async () => {
    // The executor is a constructor parameter precisely so a caller that needs this
    // write inside a larger unit of work can supply the transactional one.
    const outer = new RecordingExecutor();

    await outer.transaction(async (tx) => {
      const subject = new MysqlPromotionRepository(tx, unreachedValueRounder);

      await subject.saveRoundingRule(makeRule());
    });

    expect(outer.transactionCount).toBe(1);
    expect(outer.mutations).toHaveLength(1);
    expect(outer.mutations[0]?.inTransaction).toBe(true);
  });

  it('propagates a driver failure rather than reporting success', async () => {
    // The legacy `super.save` signalled failure by raising, and a boolean would lose
    // the reason.
    const executor = new RecordingExecutor();
    const failing: PreparedStatementExecutor = {
      // The probe answers normally, so the failure below is unambiguously the WRITE.
      execute: () => Promise.resolve([]),
      executeMutation: () => Promise.reject(new Error('duplicate key')),
      transaction: (work) => work(executor),
    };
    const subject = new MysqlPromotionRepository(failing, unreachedValueRounder);

    await expect(subject.saveRoundingRule(makeRule())).rejects.toThrow('duplicate key');
  });
});
